### ISSUE TITLE
API: Any chance we can make option names/values from CLI equal to those in erlfmt:format_file/3?

### ISSUE THREAD

**Issue by elbrujohalcon** [WhatsApp/erlfmt#113]
In the CLI (and `rebar.config`) we have `require_pragma`, `insert_pragma` and `print_width`, but `erflmt:format_file/3` that now accepts a proplist (which is awesome! ❤️ ) expects `pragma` and `width` as keys.
Would you consider using the same schema for both?

**Comment by awalterschulze** [comment]
Thanks for bringing this up.  We need to look at this and include rethinking how the rebar.config works right now.  This might take a while, sorry for the delay.

**Comment by awalterschulze** [comment]
I think we can rename `width` to `print_width` without any issues https://github.com/WhatsApp/erlfmt/pull/200

**Comment by awalterschulze** [comment]
The problem with `insert_pragma` and `require_pragma` is that they both can't be true at the same time and `-type pragma() :: require | insert | ignore.` perfectly encodes this, while `insert_pragma :: boolean() + `require_pragma :: boolean()` contains this possible error.

But on the command line, `--require-pragma` and `--insert-pragma` are consistent with `prettier`'s API, but also is strictly nicer, than `--pragma=require` and `--pragma=insert`.

This is the dilemma I am wondering about.

**Comment by elbrujohalcon** [comment]
Sorry… what's `prettier`?

**Comment by awalterschulze** [comment]
Ah no worries, I also didn't know until recently.

Prettier is a javascript formatter

https://prettier.io/docs/en/options.html#require-pragma

**Comment by elbrujohalcon** [comment]
In `rebar.config` options you use `{pragma, require | insert | ignore}`, right?

**Comment by elbrujohalcon** [comment]
If that's so… I can totally live with that and state clearly in `rebar3_format`'s README that the available options match the ones you can add in your `rebar.config`'s `erlfmt` section, not the options for the CLI.

**Comment by awalterschulze** [comment]
No in `rebar.config` we stay true to the command line arguments
https://github.com/WhatsApp/erlfmt/blob/master/doc/RebarUsage.md

```
{erlfmt, [
    check,
    require_pragma,
    verbose,
    {print_width, 100},
    {files, ["{src,include,test}/*.{hrl,erl,app.src}", "rebar.config"]}
]}
```

**Comment by elbrujohalcon** [comment]
Well… that's basically the issue :)

**Comment by awalterschulze** [comment]
Yes I think you are onto something :)

**Comment by awalterschulze** [comment]
After thinking this through again, we really do not want to compromise our function API to allow more options that the function actually supports, by allowing, for example `insert_pragma` and `require_pragma` to be true at the same time.

On the other hand, on the command line it won't be ergonomic to say `--pragma=insert`, when `--insert-pragma` is more natural.

Most users will be using a combination of command line and rebar config and not look at the functions, so having a consistent experience with command line is more important than having a consistent experience with the function API.

Given these constraints, I think the current state of `erlfmt` is the happy compromise and I will be closing this issue.

I hope having these small translation functions at the integration point in rebar3_format isn't too much trouble to maintain.
Sorry for the inconvenience.

**Comment by elbrujohalcon** [comment]
🤷
