### ISSUE TITLE
erlfmt is not fully erlfmted

### ISSUE THREAD

**Issue by awalterschulze** [WhatsApp/erlfmt#12]
How about we format the erlfmt code using erlfmt in the github action and then call `git diff --exit-code .`, which will result in exit code 1, if the pull request is not formatted.

This way we don't regress and keep erlfmt codebase formatted itself.

**Comment by michalmuskala** [comment]
Adding a `--check` command is on my agenda of things to do

**Comment by awalterschulze** [comment]
So `--check` wouldn't do any actual formatting in place, only check that potential formatted code would be different from input code and print out a actionable error message?

**Comment by awalterschulze** [comment]
First implement https://github.com/WhatsApp/erlfmt/issues/14 and the implement this using `--check`
