### ISSUE TITLE
Warnings: Warn about overlong lines?

### ISSUE THREAD

**Issue by ampleyfly** [WhatsApp/erlfmt#120]
In some cases, erlfmt produces lines longer than the print-width (this could be inevitable, for example with very long identifiers).
Would it be desirable to issue a warning about such lines?

**Comment by awalterschulze** [comment]
Interesting, maybe it would be nice, given the `--verbose` flag was passed to erlfmt. Something to think about.  Thank you for the idea.

**Comment by awalterschulze** [comment]
@ampleyfly how do you feel about implementing this?

We think this would be a good feature, but given our current priorities, we don't see when we will have time to do it.

**Comment by ampleyfly** [comment]
Sure, I will have a go at it when I have the time.

**Comment by ampleyfly** [comment]
My approach so far is to check the lengths of the lines in the formatted output, and generating warnings that are only shown in verbose mode. This works well when formatting a whole file, since the line numbers can be inferred.
However, there doesn't seem to be any tests for the format_file function.
Is it reasonable to refer to lines in format_string by number, too? What about format_range? Is this functionality desired there, too?

**Comment by awalterschulze** [comment]
The `format_file` function is not tested directly, but we do test it using `stdio` and `smoke` tests.
Although now that `format_file` returns the formatted content, there is no reason we can't start doing that.

`format_range` is not well supported yet, but I could imagine that this is where an IDE might want to hook in and then these overlong line warnings could also be useful.

So yes I think you can refer to lines in format_string,
but I guess this brings up the format of the warnings I guess I was expecting the line (string) to be printed out, saying this line is overlong, were you thinking line numbers or both?

**Comment by ampleyfly** [comment]
The current format is "<FileName>:<Line>: Line too long (<Length> > <PrintWidth>)", using the existing format_error_info functions.

**Comment by awalterschulze** [comment]
Aha, sorry I forgot about that, that should be fine, although it would be nice to include the lines content.
