### ISSUE TITLE
erlfmt is not idempotent

### ISSUE THREAD

**Issue by lpgauth** [WhatsApp/erlfmt#121]
Hi.
I'm experimenting with erlfmt on our main code base and I've found that the results change if I re-run the formater. I tried `v0.6.0` and `master`.

rebar.config:
```
{erlfmt, [
    write,
    {files, "{src,include,test}/**/*.{hrl,erl}"}
]}.
```

For example, here's a block that change every time I execute erlfmt:

```erlang
-    Impressions = [
-        {Impression#bid_imp.id, []} || Impression <- RtbReq#rtb_req.bid_request#bid_req.imp],
+    Impressions = [{Impression#bid_imp.id, []}
+        || Impression <- RtbReq#rtb_req.bid_request#bid_req.imp],
```

```erlang
-    Impressions = [{Impression#bid_imp.id, []}
-        || Impression <- RtbReq#rtb_req.bid_request#bid_req.imp],
+    Impressions = [
+        {Impression#bid_imp.id, []} || Impression <- RtbReq#rtb_req.bid_request#bid_req.imp],
```

**Comment by michalmuskala** [comment]
This indeed is a bug, the formatter should definitely be idempotent. But it seems like there's something very strange going on, a format such as:
```erl
    Impressions = [
        {Impression#bid_imp.id, []} || Impression <- RtbReq#rtb_req.bid_request#bid_req.imp],
```
like you show produced in the second example should never be possible.

Do you have some more complete reproduction example I could run? Using just this snippet I wasn't able to reproduce

**Comment by lpgauth** [comment]
It's normal you can't reproduce since there's no bug :) 

I updated the version to be used in the rebar.config, but it looks like it doesn't actually check the version since it's not in the `rebar.lock`. After nuking `_build/default/plugins` I cannot reproduce anymore.

**Comment by michalmuskala** [comment]
Ah, yes, plugin versioning in rebar is a bit of a mystery to me.
