### ISSUE TITLE
Make indent configurable?

### ISSUE THREAD

**Issue by dlesl** [WhatsApp/erlfmt#122]
Hi, great project! I was just wondering if you'd considered making the indent configurable? Two spaces is a very popular indentation depth. I tried changing `-define(INDENT, 4).` to `2` and it still seems to work :)

**Comment by elbrujohalcon** [comment]
@michalmuskala please let me know if I am crossing a line here, but...

@dlesl erlfmt is an **opinionated** formatter. If you prefer a configurable/customizable one... Maybe you should check [rebar3 format](https://github.com/adroll/rebar3_format). :)

**Comment by michalmuskala** [comment]
Yes, @elbrujohalcon is correct. One of the explicit goals of erlfmt is to have as little options as possible
