### ISSUE TITLE
Comments: insert_expr_list is sometimes used incorrectly and moves some comments

### ISSUE THREAD

**Issue by michalmuskala** [WhatsApp/erlfmt#125]
```erlang
%% from https://github.com/erlang/otp/blob/66b28bdd51899b60e0bb44d46ae4d0ae6b89601f/lib/compiler/test/trycatch_SUITE.erl#L1107-L1118
grab_bag_3() ->
    try 2 of
        true ->
            <<
              "" || [V0] = door
            >>
    catch
        error:true:V0 ->
            []
            %% The default clause here (which re-throws the exception)
            %% would not return two values as expected.
    end =:= (V0 = 42).
```

```
=ERROR REPORT==== 2-Sep-2020::14:40:35.075619 ===
Error in process <0.70.0> with exit value:
{unsupported,
    [{erlfmt_format,do_expr_to_algebra,
         [{comment,
              #{end_location => {11,56},location => {10,13}},
              ["%% The default clause here (which re-throws the exception)",
               "%% would not return two values as expected."]}],
         [{file,"/Users/micmus/github/WhatsApp/erlfmt/src/erlfmt_format.erl"},
          {line,224}]},
     {erlfmt_format,expr_to_algebra,1,
         [{file,"/Users/micmus/github/WhatsApp/erlfmt/src/erlfmt_format.erl"},
          {line,110}]},
     {erlfmt_format,try_after_to_algebra,1,
         [{file,"/Users/micmus/github/WhatsApp/erlfmt/src/erlfmt_format.erl"},
          {line,705}]},
     {erlfmt_format,try_to_algebra,4,
         [{file,"/Users/micmus/github/WhatsApp/erlfmt/src/erlfmt_format.erl"},
          {line,697}]},
     {erlfmt_format,expr_to_algebra,1,
         [{file,"/Users/micmus/github/WhatsApp/erlfmt/src/erlerlfmt
```

**Comment by michalmuskala** [comment]
Command I used to find this:

```
_build/release/bin/erlfmt ~/github/erlang/otp/lib/*/{src,include,test}/*.{e,h}rl > /dev/null
```

**Comment by awalterschulze** [comment]
Looking into this there is another problem
Try to format this:
```erlang
try 2 of
    true -> ok
catch
    _ ->
        undefined
        %% after catch
after
    ok
    %% after after
end
```
We get:
```erlang
try 2 of
    true -> ok
catch
    _ ->
        undefined
after
    %% after catch

    ok
    %% after after
end
```

**Comment by awalterschulze** [comment]
A smaller reproducing example, for the original issue
```erlang
?assertSame(
        "try 2 of\n"
        "    true -> ok\n"
        "catch\n"
        "    _ ->\n"
        "        undefined\n"
        "        %% after catch\n"
        "end\n"
    ),
.
```

**Comment by awalterschulze** [comment]
Here is another example:

```erlang
-type bar() :: fun(
    (
        %% foo
        ...
        %% after
    ) -> float()
).
```

That is formatted to:
```erlang
-type bar() :: fun(
    (
        %% foo
        ...
    ) ->
        %% after
        float()
).
```

**Comment by awalterschulze** [comment]
This looks acceptable, but just a little weird
```erlang
?assertFormat(
        "receive\n"
        "    1 -> ok\n"
        "    %% after receive\n"
        "after\n"
        "    0 -> ok\n"
        "    %% after after for receive\n"
        "end\n",
        "receive\n"
        "    1 -> ok\n"
        "%% after receive\n"
        "\n"
        "after 0 ->\n"
        "    ok\n"
        "    %% after after for receive\n"
        "end\n"
    ),
```

**Comment by awalterschulze** [comment]
The problem seems to be in recomment's `insert_expr_list` function or at least that is how I am finding these examples.

**Comment by michalmuskala** [comment]
I think, I know what's going on. In case there's no `after`, then `catch` clauses should use `insert_expr_container` rather than `insert_expr_list` in here:

https://github.com/WhatsApp/erlfmt/blob/7abee6bb4cb699c9c61ed1e83774c5196661c111/src/erlfmt_recomment.erl#L218-L219

As to the second issue - comments from `catch` moving to `after`. The issue seems more complex. The basic problem is that as far as locations in AST are concerned the last location for the "catch" part is the last token of the last clause, while the next location is already the first token of the `after` part. To handle this correctly we'd need to amend the location of the last `catch` clause to account for the space between the last token and the `after` token. Today this space is not accounted for and so just folded into the next position - before the first expression in `after`.

**Comment by awalterschulze** [comment]
Github is not that smart :)

**Comment by awalterschulze** [comment]
More working has been done on this branch https://github.com/WhatsApp/erlfmt/compare/receive_clauses?expand=1 , but we think this might be going in the wrong direction

**Comment by awalterschulze** [comment]
Spoke with @michalmuskala again
Seems we need to look at every use of `insert_expr_list`, where it is not last.
The only two cases which are left are:
  - `spec_clause` with Guards
  - `receive` with After
 These fixes should be mechanically comparable to the last two pull requests: #218 and #242

**Comment by awalterschulze** [comment]
`spec_clause` completed only `receive` with After is left.
