### ISSUE TITLE
Binary Operators: Last binary operator not formatted consistently

### ISSUE THREAD

**Issue by seriyps** [WhatsApp/erlfmt#136]
Hi. I tried to run it on my pet-project. Need to get used to a new style now :-) Looks great overall, thanks!
Found some strange example:

```diff
@@ -88,9 +100,16 @@ text_spec2char_ratio(Bin) ->
     NSpec = s2c(Bin, 0),
     NSpec / Size * 100.
 
-s2c(<<C, Rest/binary>>, Acc) when C == $\s orelse C == $\t orelse C == $\r orelse C == $\n
-                                  orelse C == $\;  orelse C == $\$ orelse C == $\>
-                                  orelse C == $\< orelse C == $\/ ->
+s2c(<<C, Rest/binary>>, Acc) when
+    C == $\s orelse
+        C == $\t orelse
+        C == $\r orelse
+        C == $\n orelse
+        C == $\; orelse
+        C == $\$ orelse
+        C == $\> orelse
+        C == $\< orelse C == $\/
+->
     s2c(Rest, Acc + 1);
 s2c(<<_C/utf8, Rest/binary>>, Acc) ->
     s2c(Rest, Acc);
```
* Why all the `orelse`s are on individual lines, but last one has 2 `C == $\< orelse C == $\/`. It looks inconsistent.
* Why single `->` on a newline?
* Minor: 1st `orelse` clause: `C == $\s orelse` has different indentation than others (guess most of other editors do the same, but I never understood why)

**Comment by michalmuskala** [comment]
Hi Sergey,

Thank you for trying out erlfmt!

We documented the reasons for choosing this formatting of when in [a formatting decision document](https://github.com/WhatsApp/erlfmt/blob/master/doc/FormattingDecisionWhenMultilineGuards.md), TL;DR is: it allows easily tell body & guards apart, it minimises diffs when something changes (like the function name), and it minimises initial indentation for the guard, so more expressions can potentially fit without breaking.

The last orelse clause formatted like that looks weird indeed. If you manually insert a newline after the last `orelse` the formatter will respect this and preserve it making the format consistent.

As for the initial `orelse` a fully consistent formatting would be to indent on every broken line, so it would result in something like:
```erl
    C == $\s orelse
        C == $\t orelse
            C == $\r orelse
                C == $\n orelse
                    ...
```
but that looks very weird. To avoid this erlfmt does not increase the indentation beyond the first break as long as the operator stays the same.

**Comment by seriyps** [comment]
Ok, I see. Should I keep it open for the "orelse clause formatted like that looks weird indeed" part?

**Comment by awalterschulze** [comment]
Yes I think, I would like to take a look at `C == $\< orelse C == $\/`
I think I would like to check why we chose to need a newline from the user.

**Comment by awalterschulze** [comment]
This was also brought up in issue https://github.com/WhatsApp/erlfmt/issues/149

> ```
> [
>     "\"" ++ binary_to_list(A2) ++ "\" -> \"" ++ binary_to_list(A1) ++ "\" " ++ graphviz_edge_label(L)
>     || {_, A1, A2, L} <- Es
> ]
> ```
> 
> gets formatted into
> 
> ```
>     [
>         "\"" ++
>             binary_to_list(A2) ++
>             "\" -> \"" ++ binary_to_list(A1) ++ "\" " ++ graphviz_edge_label(L)
>         || {_, A1, A2, L} <- Es
>     ]
> ```
> 
> I would expect something like
> 
> ```
>     [
>         "\"" ++
>             binary_to_list(A2) ++
>             "\" -> \"" ++
>             binary_to_list(A1) ++
>             "\" " ++ graphviz_edge_label(L)
>         || {_, A1, A2, L} <- Es
>     ]
> ```
> 
> with similar reasoning as in [#136 (comment)](https://github.com/WhatsApp/erlfmt/issues/136#issuecomment-691654159).
> 
> Ideally it should like
> 
> ```
>     [
>         "\"" ++
>             binary_to_list(A2) ++
>             "\" -> \"" ++
>             binary_to_list(A1) ++
>             "\" " ++
>             graphviz_edge_label(L)
>         || {_, A1, A2, L} <- Es
>     ]
> ```
> 
> Note the final `++` argument is on an extra line.

**Comment by seriyps** [comment]
Another strangely-looking example: https://github.com/seriyps/logger_journald/blob/5b57951917975760d09134728bfd0e1b11cbe96e/src/logger_journald_h.erl#L211-L215

```erlang
convert_meta(Key, Value) when
    is_list(Key) orelse is_binary(Key),
    is_list(Key) orelse
        is_binary(Value) orelse
        is_atom(Value) orelse
        is_integer(Value)
->
```

**Comment by awalterschulze** [comment]
Thank you for reporting, these examples are very useful.

**Comment by awalterschulze** [comment]
> Another strangely-looking example: https://github.com/seriyps/logger_journald/blob/5b57951917975760d09134728bfd0e1b11cbe96e/src/logger_journald_h.erl#L211-L215
> 
> ```erlang
> convert_meta(Key, Value) when
>     is_list(Key) orelse is_binary(Key),
>     is_list(Key) orelse
>         is_binary(Value) orelse
>         is_atom(Value) orelse
>         is_integer(Value)
> ->
> ```

When I took a second look, this one seems fine.
It is not breaking the first `orelse`, since it is considered separately, because the comma is grouping.
`is_list(Key) orelse is_binary(Key),` together.

The next part also looks formatted correctly:
```
is_list(Key) orelse
        is_binary(Value) orelse
        is_atom(Value) orelse
        is_integer(Value)
```

So I think it looks funny for the right reasons and makes us notice the comma

Maybe I am missing what you think looks strange?

**Comment by seriyps** [comment]
Ouch, sorry, indeed, forgot about comma. Makes sense now!
