### ISSUE TITLE
Error on macro definition

### ISSUE THREAD

**Issue by yjh0502** [WhatsApp/erlfmt#137]
I know, the code looks super weird but for some reason I ended up with the code and `erlfmt` complains about it :(
Here's a code
```erl
-module(foo).

-export([foo/0]).

-define(FOO,
    foo => bar
).

foo() ->
    #{
        ?FOO
    }.
```

and error message from `rebar3 fmt`

```
src/foo.erl:5:9: syntax error before: '=>'
src/foo.erl:11:5: syntax error before: '}'
```

BTW thanks for sane code formatter for Erlang, it was a major missing productivity tool.

**Comment by awalterschulze** [comment]
Thanks again @yjh0502 for a great bug report :)
