### ISSUE TITLE
Error on macro with binary construction

### ISSUE THREAD

**Issue by yjh0502** [WhatsApp/erlfmt#138]
Code
```erl
-module(foo).

-export([foo/0]).

-define(FOO(), "foo").

foo() ->
    <<"" ?FOO()>>.
```

output from `rebar3 fmt`
```
src/foo.erl:8:14: syntax error before: '('
```

It seems that `erlfmt` doesn't understand constant string concatenation with macro invocation. It works if there's no macro invocation (`<<"" ?FOO>>` instead of `<<"" ?FOO()>>`) or no string concatenation (`<<?FOO()>>` instead of `<<"" ?FOO()>>`). `<<"", ?FOO()>>` also works.

**Comment by awalterschulze** [comment]
Thank you @yjh0502 for the bug report.  Thank you for also providing a great example, which made it possible for @michalmuskala to fix.
