### ISSUE TITLE
Calls: Spacing around parenthesis

### ISSUE THREAD

**Issue by david-kubecka** [WhatsApp/erlfmt#147]
I know that in the erlang codebase it's overwhelmingly standard to not put any spacing around parenthesis (in function calls, collections, tuples, ...). But in codebases with lot of e.g. function calls chaining a single space can make the code slightly clearer (at least to my eyes). Very simple example:
```
binary_to_number( Bin ) ->
    string_to_number( binary_to_list( Bin ) ).
```
vs.
```
binary_to_number(Bin) ->
    string_to_number(binary_to_list(Bin)).
```

- Is it feasible to make the spacing configurable?
- If yes would you be willing to actually make it configurable?

**Comment by awalterschulze** [comment]
`erlfmt` is an opinionated formatter, so even if this was possible, which it probably is, it is extremely likely that we will not make this configurable.  Personally, I have quite a few different preferences than the current `erlfmt` format, but we value the conformity more than our own preferences.

On the other hand, a discussion about which way to go for all `erlfmt` users would be on the table.
I never considered:
```erlang
binary_to_number( Bin ) ->
    string_to_number( binary_to_list( Bin ) ).
```
But it does look quite nice.

I do think though, that this style would be tough to sell, given how unpopular this style is ... I assume.
If you can gather data that shows my assumption is wrong, then I think this would be a very interesting discussion.
Does that make sense?

**Comment by michalmuskala** [comment]
I agree we shouldn't make this configurable given the goals of erlfmt. Combined with the fact that this style is rather unpopular in the Erlang community, I don't think we should change the behaviour.

**Comment by david-kubecka** [comment]
Sure, definitely do not change the default. And perhaps even if I'm very much used to the spacing here the overall benefits of consistent formatting could perhaps win me over (as generally I like most of your opinionated decisions).

You know, your project really looks interesting so I'm willing to devote some time to it. Therefore I'm trying to gain as much understanding of the general attitude to the problem to speed up my evaluation period :-)

**Comment by awalterschulze** [comment]
Thank you so much @david-kubecka we really appreciate your effort and time.

Do you think we can close this issue?

**Comment by awalterschulze** [comment]
I hope it is okay to close this issue.
Let me know if you would like to discuss this more.

**Comment by david-kubecka** [comment]
Sorry for late notice - my vacation finished ;-) Yes, it's ok you have closed the issue.
