### ISSUE TITLE
List comprehensions: Formatting of long list comprehension expressions

### ISSUE THREAD

**Issue by david-kubecka** [WhatsApp/erlfmt#148]
I just want to confirm your point on formatting this:
```
[function_with_long_name(A, Param1, Param2, Param3) || A <- a_generator()]
```
Currently it's formatted into
```
[
    function_with_long_name(A, Param1, Param2, Param3)
    || A <- a_generator()
]
```
which to me occupies too much vertical space. Is it really intended so? Did you consider other options, e.g.
```
[function_with_long_name(A, Param1, Param2, Param3)
|| A <- a_generator()]
```
?

**Comment by awalterschulze** [comment]
Thank you @david-kubecka for pointing out another formatting decision we should explain.
You are on a roll :D

**Comment by michalmuskala** [comment]
Formatting comprehensions is something I struggled with a lot initially when building the formatter, and later when we were finalising it with @awalterschulze. I'm not a huge fan of the current solution, but it seems the most consistent with how we format everything else (lists in particular). 

In general my opinion is that it's impossible to make multiline comprehensions look nice with the current syntax.

**Comment by ampleyfly** [comment]
I think list comprehensions which are not very small should be formatted like
```
[function_with_long_name(A, Param1, Param2, Param3)
 || A <- a_generator(),
    some_check(A)]
```

**Comment by awalterschulze** [comment]
Cool we can use this as an alternative to consider in the document.  Thank you :)

**Comment by awalterschulze** [comment]
I think before we discuss list comprehensions, I think we should first discuss how lists are formatted.  I suspect we would want these two decisions to be consistent with each other.
Here we try to explain our current reasoning for how we format lists with erlfmt
https://github.com/WhatsApp/erlfmt/blob/ffa4531b9f9ae25d9f6e2160333e38fe05175636/doc/FormattingDecisionLists.md

**Comment by paulo-ferraz-oliveira** [comment]
@awalterschulze. Is the 1-space in this example "inconsistent" with a 4-space oriented format?

```erlang
[function_with_long_name(A, Param1, Param2, Param3)
 || A <- a_generator(),
    some_check(A)]
```

e.g. (it would become)
```erlang
[function_with_long_name(A, Param1, Param2, Param3)
    || A <- a_generator(),
        some_check(A)]
```

I'm thinking about writing code where I don't want to constantly keep aligning stuff by hand (I do use tab=4 spaces) to not be challenged by the formatter later.

Just a thought.

**Comment by awalterschulze** [comment]
Yes, we have been thinking the same thing.
Given the 4 space decision that would be the case.

Although I think the multiline list document, I linked, can have another influence on this format.

**Comment by awalterschulze** [comment]
Started a formatting decision document for list comprehensions specifically https://github.com/WhatsApp/erlfmt/pull/212

**Comment by maxno-kivra** [comment]
I tried erlfmt out today, and as someone that like to use list comprehensions I thought I should leave some feedback. First off, this is an amazing tool, thanks for making my life better ❤️ 

The code in question gets formatted like this:

```erlang

defines_protocol(Module, Function, Arity) when
    is_atom(Module) andalso is_atom(Function) andalso is_integer(Arity)
->
    case defines_protocol(Module) of
        false ->
            false;
        true ->
            [ok] =:=
                [
                    ok
                    || {Fun, FunArity} <- Module:protocol_info(),
                       Fun =:= Function,
                       FunArity =:= Arity
                ]
    end.
```

But as @paulo-ferraz-oliveira pointed out, the lines under `||` get indented just 3 spaces. Which makes further editing weird. I personally prefer to keep the `||` divider on a separate line, aligned with the brackets:

```erlang
defines_protocol(Module, Function, Arity) when
    is_atom(Module) andalso is_atom(Function) andalso is_integer(Arity)
->
    case defines_protocol(Module) of
        false ->
            false;
        true ->
            [ok] =:=
                [
                    ok
                || 
                    {Fun, FunArity} <- Module:protocol_info(),
                    Fun =:= Function,
                    FunArity =:= Arity
                ]
    end.
```

This keeps stuff aligned without depending on variable names, and also visually groups the two halves of the comprehension.

If I were to format this by hand I would keep the `[` on the same line as `[ok] =:= [` and dedent the others. But for consistency I'll gladly sacrifice saving an indentation level/line.

**Comment by awalterschulze** [comment]
Really good to get another opinion on this thank you :)

We are already getting complaints about list comprehensions not being compact enough, this suggestion makes it even less compact, but to be fair we also get complaints about the indentation of 3 that even we are not happy about.

@michalmuskala and I will take another look at this.

**Comment by awalterschulze** [comment]
We have thought again, it is quite tough to make list comprehensions look really good, but your point of 3 spaces is something that has also come up before, so we would like to try and solve it, while trying to somewhat limited the space the list comprehension takes.

Here is another proposal:
```erlang
[ 
    ok 
 || {Fun, FunArity} <- Module:protocol_info(),
    Fun =:= Function,
    FunArity =:= Arity 
]

[ 
    begin
        X, Y
    end
 || {Fun, FunArity} <- Module:protocol_info(), Fun =:= Function,
]
```

What do you think?

**Comment by maxno-kivra** [comment]
Indenting the pipes, very clever. That works for me (even though I prefer something more spacious 😉).

Another variant would be to add a space _after_ the pipes. This would make all left side indentation consistent. Better? Worse?

```erlang
[ 
    ok 
||  {Fun, FunArity} <- Module:protocol_info(),
    Fun =:= Function,
    FunArity =:= Arity 
]

[ 
    begin
        X, Y
    end
||  {Fun, FunArity} <- Module:protocol_info(), Fun =:= Function,
]
```

**Comment by awalterschulze** [comment]
Actually that was our first "new" idea, but then we were worried about the user having to type `2` spaces after the two pipes.  Still on the fence between these two, but good to hear support for these cases.

**Comment by awalterschulze** [comment]
I have created an updated version of formatting for list comprehensions https://github.com/WhatsApp/erlfmt/pull/249
It is something we can look at while to help inform our decision

**Comment by maxno-kivra** [comment]
I prefer that all code is right aligned, and by that i mean the first non-whitespace character is on a column divisible by 4. This is because my editor, and I suspect most others, offer indentation assistance. Entering a new line, or using tab/shift+tab does that.

So if you indent/dedent a block of code it will break the double pipe indentation. Later when I run `erlfmt` it gets corrected. But on the other hand, when I write code while using a formatter like `erlmft` I tend to be a bit sloppy and let it do its thing. Especially for whitespace around operators/parenthesis. So I would be more surprised that the line got reindented, then that an additional space got added.

Depending on setting, use of language server etc, code folding usually works (or falls back to) indentation. I would assume this translates into the entire comprehension being collapsed with the pipes indented one extra, and each part collapsed in my version. Which is better is up to debate, but might be good to have in mind.

**Comment by awalterschulze** [comment]
I am struggling a bit to understand.  Does this mean you prefer the format as it is currently, or with the change in the pull request:

```
[ 
    ok 
 || {Fun, FunArity} <- Module:protocol_info(),
    Fun =:= Function,
    FunArity =:= Arity 
]
```

**Comment by maxno-kivra** [comment]
Sorry for the confusion, I prefer:

```erlang
[
    Value
||  {ok, Value} <- List,
    Value =/= bad
]
```

Note the double space _after_ the double pipes, as opposed to the suggested extra space _before_ the double pipes.

Does this make sense now?

**Comment by awalterschulze** [comment]
After trying it out, I found a problem with:
```erlang
[
    Value
||  {ok, Value} <- List,
    Value =/= bad
]
```
At least, as far as I can see, it is tough to do with our layout algorithm, let me try to explain:

When this list comprehension doesn't need to break it would be layed out as:
```erlang
[ Value ||  {ok, Value} <- List, Value =/= bad ]
```
Now there is two spaces between `||` and `{ok, Value...`, which is not what we want.
We only want to the two spaces when the list comprehension breaks over multiple lines.

The layout algorithm we have is greedy, so by the time it is found that the list comprehension does not fit on one line, it might already be past the two spaces at for example `Value =/= bad`, but we can't back track and replace two spaces with one.

This is not a problem with:
```erlang
[
    Value
 || {ok, Value} <- List,
    Value =/= bad
]
```
because in both cases `||` had one space on each side:
```erlang
[ Value || {ok, Value} <- List, Value =/= bad ]
```
I hope that makes sense

**Comment by awalterschulze** [comment]
We have merge the solution for:
```
[
    Value
 || {ok, Value} <- List,
    Value =/= bad
]
```
simply as explained that the technical solution for:
```
[
    Value
||  {ok, Value} <- List,
    Value =/= bad
]
```
would add a lot of complexity and personally we couldn't decide which we prefer.

I have also updated the formatting decision document to include both examples and explain our reasoning.
