### ISSUE TITLE
List comprehensions: Inconsistent indentation in list comprehension

### ISSUE THREAD

**Issue by david-kubecka** [WhatsApp/erlfmt#149]
```
[
    "\"" ++ binary_to_list(A2) ++ "\" -> \"" ++ binary_to_list(A1) ++ "\" " ++ graphviz_edge_label(L)
    || {_, A1, A2, L} <- Es
]
```
gets formatted into
```
    [
        "\"" ++
            binary_to_list(A2) ++
            "\" -> \"" ++ binary_to_list(A1) ++ "\" " ++ graphviz_edge_label(L)
        || {_, A1, A2, L} <- Es
    ]
```
I would expect something like
```
    [
        "\"" ++
            binary_to_list(A2) ++
            "\" -> \"" ++
            binary_to_list(A1) ++
            "\" " ++ graphviz_edge_label(L)
        || {_, A1, A2, L} <- Es
    ]
```
with similar reasoning as in https://github.com/WhatsApp/erlfmt/issues/136#issuecomment-691654159.

Ideally it should like
```
    [
        "\"" ++
            binary_to_list(A2) ++
            "\" -> \"" ++
            binary_to_list(A1) ++
            "\" " ++
            graphviz_edge_label(L)
        || {_, A1, A2, L} <- Es
    ]
```
Note the final `++` argument is on an extra line.

**Comment by awalterschulze** [comment]
Thank you @david-kubecka for the example.  This is great feedback.
I think this is similar to https://github.com/WhatsApp/erlfmt/issues/136
I will take a look.

**Comment by awalterschulze** [comment]
In the interim you can try to add a newline after the final `++` and check if `erlfmt` preserves it for you.

**Comment by michalmuskala** [comment]
Yes, this is exactly the same issue as #136, but in a different context. We should merge them.

**Comment by awalterschulze** [comment]
Yes I agree, I have copied the example to the duplicate issue https://github.com/WhatsApp/erlfmt/issues/136
Closing this.
I hope that makes sense.
