### ISSUE TITLE
Add @format pragma handling

### ISSUE THREAD

**Issue by michalmuskala** [WhatsApp/erlfmt#15]
We should add a way to adopt formatter gradually on a set of files. 
This would be simplest done requiring the first comment block to contain a `@format` annotation.  Please see https://prettier.io/docs/en/cli.html#--require-pragma for an example.

Additionally add a `--insert-pragma` command that formats a file and adds a pragma for easier step-by-step adoption. Please see https://prettier.io/docs/en/cli.html#--insert-pragma for an example.

**Comment by awalterschulze** [comment]
I can take this?

**Comment by michalmuskala** [comment]
Yeah, go ahead

**Comment by awalterschulze** [comment]
Ah yes I forgot we can assign tasks :)
Thank you.

**Comment by awalterschulze** [comment]
Examples of inserted pragmas:

file.css
```css
/**
 * Copyright bla
 *
 * bla
 * bla
 * bla
 *
 * @format
 */
```

file.js
```javascript
/**
 * Copyright bla
 *
 * bla
 * bla
 *
 * @someotherpragma
 * @format
 */
```

file.php
```hack
<?hh // strict
// Copyright bla
// @format
```
