### ISSUE TITLE
Inconsistency in lists formatting

### ISSUE THREAD

**Issue by david-kubecka** [WhatsApp/erlfmt#152]
I would expect that these two expressions end up formatted in the same way (note the different placement of `|`:
```
[
    {'extra_object_a' | 'extra_object_b' | 'extra_list_a' | 'extra_list_b', Path, term()}
    | {diff, Path, term(), term()}
].
[
    {'extra_object_a' | 'extra_object_b' | 'extra_list_a' | 'extra_list_b', Path, term()} |
    {diff, Path, term(), term()}
].
```
In reality the formatter leaves both of them untouched.

**Comment by awalterschulze** [comment]
I had to add 4 spaces to fit this into a spec to I removed 4 spaces from `extra_list_b`, but for me `erlfmt` does actually move the pipe `|` back to the previous line, if it can fit it in

```erlang
?assertFormat(
        "-spec a(\n"
        "    [\n"
        "        {'extra_object_a', 'extra_object_b' | 'extra_list_a' | 'min4_l_b', Path, term()}\n"
        "        | {diff, Path, term(), term()}\n"
        "    ]\n"
        ") -> ok.\n",
        "-spec a(\n"
        "    [\n"
        "        {'extra_object_a', 'extra_object_b' | 'extra_list_a' | 'min4_l_b', Path, term()} |\n"
        "        {diff, Path, term(), term()}\n"
        "    ]\n"
        ") -> ok.\n"
    , 100),
```

**Comment by awalterschulze** [comment]
Maybe I misunderstood?

**Comment by michalmuskala** [comment]
I don't think we should be producing formats with leading `|`, IIRC we format all operators at the end of the line

**Comment by david-kubecka** [comment]
@awalterschulze I'm testing all my examples by putting them into separate file, formatting them directly with the `erlfmt` binary and then just looking at the results. Perhaps putting my example inside a spec makes a difference?

**Comment by michalmuskala** [comment]
Formatting the examples on their own as:
```erl
% foo.erl
[
    {'extra_object_a' | 'extra_object_b' | 'extra_list_a' | 'extra_list_b', Path, term()}
    | {diff, Path, term(), term()}
].

[
    {'extra_object_a' | 'extra_object_b' | 'extra_list_a' | 'extra_list_b', Path, term()} |
    {diff, Path, term(), term()}
].
```
Produces them without any changes, but this is accompanied by two warnings:
```
foo.erl:1:1: syntax error before: '['
foo.erl:5:1: syntax error before: '['
```

This is because erlfmt does not support types as top-level values. Only expressions are supported in such position (to support formatting of files such as `rebar.config`).

When placed in proper type position, for example like in the following:
```erl
%% foo.erl
-type foo() ::
[
    {'extra_object_a' | 'extra_object_b' | 'extra_list_a' | 'extra_list_b', Path, term()}
    | {diff, Path, term(), term()}
].

-type bar() ::
[
    {'extra_object_a' | 'extra_object_b' | 'extra_list_a' | 'extra_list_b', Path, term()} |
    {diff, Path, term(), term()}
].
```
They are both formatted consistently and produce the same output in both cases:
```erl
-type foo() :: [
    {'extra_object_a' | 'extra_object_b' | 'extra_list_a' | 'extra_list_b', Path, term()} |
    {diff, Path, term(), term()}
].

-type bar() :: [
    {'extra_object_a' | 'extra_object_b' | 'extra_list_a' | 'extra_list_b', Path, term()} |
    {diff, Path, term(), term()}
].
```

I'm going to close this now. If there's anything I missed, please reopen.

**Comment by david-kubecka** [comment]
Ahh, to be honest I didn't even realize that I'm actually working with typespecs (and not expressions) here. The syntax is so similar :-)
