### ISSUE TITLE
Tuples: Deeply nested tuples get formatted strangely

### ISSUE THREAD

**Issue by david-kubecka** [WhatsApp/erlfmt#153]
```
{{<<"key3">>}, {[{<<"true">>, true}, {<<"false">>, false}, {<<"nullqweqwewqdqwqdwqdq">>, null}, {<<"numberqweqwrqwdqd">>, 1}]}}.
```
This still formats ok (note the correct alignment of opening and closing parens):
```
{{<<"key3">>},
    {[
        {<<"true">>, true},
        {<<"false">>, false},
        {<<"nullqweqwewqdqwqdwqdq">>, null},
        {<<"numberqweqwrqwdqd">>, 1}
    ]}}.
```
But wrapping the second top level element into another tuple leads to strange results:
```
{{<<"key3">>},
    {{[
            {<<"true">>, true},
            {<<"false">>, false},
            {<<"nullqweqwewqdqwqdwqdq">>, null},
            {<<"numberqweqwrqwdqd">>, 1}
        ]}}}.
```
But perhaps it's intended. I'm not really sure here.

**Comment by michalmuskala** [comment]
I agree this looks a bit strange. Good catch!

**Comment by awalterschulze** [comment]
Maybe this is a smaller reproducing example, where the first one is fine and the second one adds surrounding curlies for the second element and the formatting goes weird:
```erlang
?assertFormat(
        "{abc, {abc, cde}}.",
        "{abc,\n"
        "    {abc,\n"
        "        cde}}.\n",
        10
    ),
    ?assertFormat(
        "{abc, {{abc, cde}}}.",
        "{abc,\n"
        "    {{abc,\n"
        "            cde}}}.\n",
        10
    ),
```

**Comment by awalterschulze** [comment]
Here is an even weirder one
```erlang
?assertFormat(
        "{abc, {{cde, def}, ghi}}.",
        "{abc,\n"
        "    {{cde,\n"
        "            def},\n"
        "        ghi}}.\n",
        10
    ).
```

**Comment by awalterschulze** [comment]
Now I wonder what the fix would look like, do we special case tuples with single elements, to always keep the curlies together and only indent once, but when we add an element, we fall back to the current format?
Same goes for `bin`

Or what do we want the output format to look like?

**Comment by awalterschulze** [comment]
After some discussion we found two more cases that look weird, we think this problem is regarding lists in tuples, probably not only lists, but at least lists look weird
```erlang
A =
        {abc, [
            cde
        ]},
A =
        {{abc, [
                cde
            ]}},
```

**Comment by michalmuskala** [comment]
With the changes proposed in #259, the original example will now be formatted as:
```erl
{
    {<<"key3">>},
    {[
        {<<"true">>, true},
        {<<"false">>, false},
        {<<"nullqweqwewqdqwqdwqdq">>, null},
        {<<"numberqweqwrqwdqd">>, 1}
    ]}
}.
```
