### ISSUE TITLE
Functions: Consider formatting "lists"-like functions differently

### ISSUE THREAD

**Issue by david-kubecka** [WhatsApp/erlfmt#158]
Generally, the problem with automatic formatters is that their results took too much vertical space without necessarily increasing readability. `erlfmt` is quite okay in this area which is an excellent result for a formatter :-). There are few areas for improvements, though. One of them is formatting of `lists`-like functions. generally functions that take an anonymous function as a parameter. Example (from the [erlang doc](http://erlang.org/doc/man/lists.html#filtermap-2)):
```
lists:foldr(fun(Elem, Acc) ->
                       case Fun(Elem) of
                           false -> Acc;
                           true -> [Elem|Acc];
                           {true,Value} -> [Value|Acc]
                       end
                end, [], List1).
```
This gets formatted into
```
lists:foldr(
    fun(Elem, Acc) ->
        case Fun(Elem) of
            false -> Acc;
            true -> [Elem | Acc];
            {true, Value} -> [Value | Acc]
        end
    end,
    [],
    List1
).
```
which is IMO still better than the original (I don't like the floating alignment of the emacs-mode). But why not produce this?
```
lists:foldr(fun(Elem, Acc) ->
    case Fun(Elem) of
        false -> Acc;
        true -> [Elem | Acc];
        {true, Value} -> [Value | Acc]
    end
end, [], List1).
```
The general rule would be to treat the anonymous fun as if `fun(...) ->` and `end` were parenthesis wrapping the body, with the rest of the parameters on the same line as the "closing" `end` parenthesis.

I think this could work even in more complex examples like:
```
dict:update(Key, fun({Min, Max, _Old}) ->
    {min(Min, Value), max(Max, Value), Value}
end, {Value, Value, Value}, Stats).

lists:map(fun
    (a) -> b;
    (b) -> c
end, Letters).
```

Obviously this needs much more thought but I hope I conveyed the idea well enough.

**Comment by awalterschulze** [comment]
Thank you for the idea and coming up with a rule.
We will come back to this later and first try to wrap up other issues, but this is very interesting.

**Comment by awalterschulze** [comment]
It might be worth considering doing this for inline functions in the first or last argument.
Today we already do it for the last argument.
But the interaction between the two can be complex and be technically challenging to implement.

Either way, we think this style, where an inline function is in the middle, might make code harder to read.
```erlang
dict:update(Key, fun({Min, Max, _Old}) ->
    {min(Min, Value), max(Max, Value), Value}
end, {Value, Value, Value}, Stats).
```

**Comment by paulo-ferraz-oliveira** [comment]
Doesn't this (as `erlfmt` does), give you a good notion of start/end for anonymous functions (and save some space while you're at it)?
```erlang
lists:foldr(
    fun(Elem, Acc) ->
        case Fun(Elem) of
            false -> Acc;
            true -> [Elem | Acc];
            {true, Value} -> [Value | Acc]
        end
    end,
    [],
    List1
).
```

I tend to use that form and sometimes end with:
```erlang
end, [], List1
```
or
```erlang
end,
[], List1
```
since I care mostly about the anonymous function content and not what "initialized" it.

**Comment by david-kubecka** [comment]
> It might be worth considering doing this for inline functions in the first or last argument.
> Today we already do it for the last argument.
> But the interaction between the two can be complex and be technically challenging to implement.

To be honest I tend to think about the problem only from the user (read dev) perspective, i.e. I intentionally ignore potential implementation complexities because
- that's your business :-)
- overall UX is much more important than the code providing it

To the point: If you already format extra an inline fun in the last argument AND it makes sense for you to do that also for the first argument then I as a user would be little surprised that it also doesn't work when it's in the middle. But if that really is not possible (for various reasons) then allowing my prefered formatting for lists:foldr would still be good progress.

**Comment by david-kubecka** [comment]
> Doesn't this (as `erlfmt` does), give you a good notion of start/end for anonymous functions (and save some space while you're at it)?

I don't see how you can make the current erlfmt (reasonably) more verbose spacewise :-) That's my primary concern here.

**Comment by awalterschulze** [comment]
We have thought about this again and would actually be very open to

```erlang
lists:map(fun
    (a) -> b;
    (b) -> c
end, Letters).
```

and

```erlang
lists:foldr(fun(Elem, Acc) ->
    case Fun(Elem) of
        false -> Acc;
        true -> [Elem | Acc];
        {true, Value} -> [Value | Acc]
    end
end, [], List1).
```

where the function is the first parameter, but we have no idea how to accomplish this.

**Comment by awalterschulze** [comment]
I am going to close the issue, but only because we do not know how to do it and we haven't received any response.
If someone knows how, they are more than welcome to jump in, we think it would be a great addition.
We also think it is possible to accomplish without break backwards compatibility, so this is even up for reopening after releasing version 1.0.0
