### ISSUE TITLE
Lists: Consider formatting long lists the same way as in function calls

### ISSUE THREAD

**Issue by david-kubecka** [WhatsApp/erlfmt#159]
Consider these two expressions:
```
[aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb, [cccccccccccccccccccccccccccccccccc]].

x(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb, [cccccccccccccccccccccccccccccccccc]).
```
They get formatted into:
```
[
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb,
    [cccccccccccccccccccccccccccccccccc]
].

x(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb, [
    cccccccccccccccccccccccccccccccccc
]).
```

So there's an apparent inconsistency between formatting function calls with long parameters and nested lists, and other "containers", e.g. lists, tuples, records and probably more. This might very well be intended and in fact makes some sense. I'm just curious to hear your explicit reasoning about this (perhaps it would to materialize it in a separate decisiion document).

**Comment by awalterschulze** [comment]
Yes this is intended.  A decision document sounds like a good idea, thank :D

**Comment by awalterschulze** [comment]
I hope this decision document has covered this case
https://github.com/WhatsApp/erlfmt/blob/master/doc/FormattingDecisionLists.md
if not please let me know what I missed
