### ISSUE TITLE
Binary Operators: Wrong alignment of boolean operators

### ISSUE THREAD

**Issue by david-kubecka** [WhatsApp/erlfmt#161]
Following is IMO well formatted. Note the extra alignment of the second `orelse` argument. That is desired because the previous operator is different.
```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa andalso
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb orelse
        cccccccccccccccccccccccccccccccccc.
```
In reality this gets formatted into
```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa andalso
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb orelse
    cccccccccccccccccccccccccccccccccc.
```
which somehow obscures the logic.

**Comment by awalterschulze** [comment]
Very interesting.
What is the operator precedence here I assume `andalso` is bound stronger than `orelse` as in:
`(a andalso b) orelse c`

**Comment by michalmuskala** [comment]
This looks like a bug to me. I believe we should be always increasing the indentation after an operator, unless it's a repeated sequence of the same operator. The rule is to increase, though, not increasing is an exception.

**Comment by awalterschulze** [comment]
Sounds good to me :)

**Comment by awalterschulze** [comment]
Looking at this again I don't know if this really is a bug.
The following tests both pass:

```erlang
?assertSame(
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA orelse\n"
        "    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB andalso\n"
        "        CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC.\n"
    ),
    ?assertSame(
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa andalso\n"
        "    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb orelse\n"
        "    cccccccccccccccccccccccccccccccccc.\n"
    ),
```

The lowercase parses as:
`{orelse, {andalso, aaaa, bbbb}, cccc}`
and the capital letter parses as:
`{orelse, AAAA, {andalso, BBBB, CCCC}`

It is clear that the capital letters need to indent, since the `andalso` is a right child of the `orelse`.
In the lowercase letter case the `aaaa` and `bbbb` are technically "equal" to the `cccc`, so having them on the same indentation level makes sense.

**Comment by awalterschulze** [comment]
If you want the identation where the orelse binds stronger then you will need parenthesis

```erlang
?assertSame(
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa andalso\n"
        "    (bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb orelse\n"
        "        cccccccccccccccccccccccccccccccccc).\n"
    ),
```

**Comment by awalterschulze** [comment]
We have added tests in #262 to show case the 4 separate cases
with and without parenthesis and swapping andalso and orelse
and all seems to format as sensibly as the expression is readable

**Comment by awalterschulze** [comment]
I think this closes the issue. 
I hope our conclusion makes sense.
