### ISSUE TITLE
Wrong treatment of inline comments

### ISSUE THREAD

**Issue by david-kubecka** [WhatsApp/erlfmt#165]
```
[x % x
, y % y
].
```
Current result:
```
% x
[
    x,
    % y
    y
].
```
Expectation:
```
[
    % x
    x,
    % y
    y
].
```
I think the problem is that you put the `x` comment above the line with the first snippet (`[`) of the original line. More correct solution would be to track the last snippet (`x,`) and put the comment above its line.

**Comment by michalmuskala** [comment]
The behaviour of comments today is very simple. They are always placed before the line (that means before all tokens that appeared on that line). We're debating changing that with some more subtle or complex behaviour in https://github.com/WhatsApp/erlfmt/issues/134, I'm going to close this issue in favour of the discussion in the other one.
