### ISSUE TITLE
Indentation: Make it compatible with OTP/Erlangs emacs mode

### ISSUE THREAD

**Issue by RoadRunnr** [WhatsApp/erlfmt#166]
OTP includes an [emacs mode](https://github.com/erlang/otp/tree/master/lib/tools/emacs). IMHO that mode is de facto default formatting for Erlang (minus the tab-vs-space thingy, maybe).

It would be great is the formating generate by that mode and erlfmt are identical.

**Comment by awalterschulze** [comment]
May I ask whether you could bring up specific issues, where `erlfmt` differs that we can talk about one by one?
In general we are open to adopting at least some of this style.

**Comment by michalmuskala** [comment]
I believe the differences are significant and in some particular cases this could amount to almost rewriting what erlfmt does. 

In particular though, if I'm not mistaken, what the emacs mode has is a re-indenter, not a full formatter. In particular it does not parse the code and primarily follows some simpler syntactical rules. In case of examples, what I think would be most useful, is to see if there are cases where code formatted by erlfmt gets re-indented by emacs.

**Comment by awalterschulze** [comment]
Another data point of someone enquiring about emacs indentation https://github.com/erlang/otp/pull/2756#discussion_r492508630

**Comment by awalterschulze** [comment]
@IngelaAndin or @RoadRunnr do you possibly have some examples as Michal was asking for above, that you are sure are indented using emacs that we can look at?

**Comment by awalterschulze** [comment]
Aligning with the emacs mode would be a very big change with how erlfmt works, particularly how lists are formatted, see the formatting decision on lists https://github.com/WhatsApp/erlfmt/blob/master/doc/FormattingDecisionLists.md

Closing this as there has not been any activity.
