### ISSUE TITLE
Comments: Trailing comments that become post comments

### ISSUE THREAD

**Issue by awalterschulze** [WhatsApp/erlfmt#168]
Reference: https://github.com/erlang/otp/pull/2756/files#r491202924

Trailing comments are moved to the line below, instead of the line above if they are bound to post comments.

```erlang
a, % trailing comment
%% post comment
```

Is formatted to
```erlang
a,
% trailing comment
%% post comment
```
instead of
```erlang
% trailing comment
a,
%% post comment
```

**Comment by michalmuskala** [comment]
This does indeed look like a bug

**Comment by awalterschulze** [comment]
Cool agreed :)

**Comment by awalterschulze** [comment]
Here is another occurrence https://github.com/awalterschulze/luerl/commit/76364ae73e82fbf78a789aa6b6cb92ab4ea36ee7#r42436065
