### ISSUE TITLE
rebar3: Crash upon `rebar3 fmt **`

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [WhatsApp/erlfmt#169]
I'm sure this syntax is wrong, but it was the first thing I tried when I ran `rebar3 fmt` and was told about `no files provided to format`.

**What was I expecting?**

As per [filelib:wildcard/1](https://erlang.org/doc/man/filelib.html#wildcard-1), to "match all files and zero or more directories and subdirectories."

Using `master`.

By the way:

* `/**`
* `src/**`

also crash.

**What was I expecting?**

That the formatter would execute, and if files had to be skipped, they would be - with a warning, stating that it can't format so and so, because "unknown file type" -, instead of crashing 😄 

Oh, I now see that it's not expected to crash, since it's in the `README.md`. Anyway, here's my report...

**Comment by paulo-ferraz-oliveira** [comment]
After adding 
```erlang
{erlfmt, [
    write,
    {files, "{src,include,test}/*.{hrl,erl}"}
]}.
```
to `rebar.config`, it's not crashing.

**Comment by awalterschulze** [comment]
I think you are right, we should still print out a better error message and not crash.
Thank you for reporting :)

**Comment by awalterschulze** [comment]
@michalmuskala 
If we land https://github.com/WhatsApp/erlfmt/pull/196
Then we can solve this issue by changing:

```
-spec do(string(), list(), list()) -> ok.
do(Name, PreferOpts, DefaultOpts) ->
    PreferParsed = parse_opts(PreferOpts),
    DefaultParsed = parse_opts(DefaultOpts),
+    DefaultFiles = parse_opts([{files, "{src,include,test}/*.{hrl,erl,app.src}"}, {files, "rebar.config"}]),
-   Parsed = resolve_parsed(PreferParsed, DefaultParsed),
+   Parsed = resolve_parsed(PreferParsed, resolve_parsed(DefaultParsed, DefaultFiles)),
    with_parsed(Name, Parsed).
```

Or something similar, depending on what we want the default to be
