### ISSUE TITLE
Spec: Formatting -spec(_).s

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [WhatsApp/erlfmt#170]
When I'm not busing `-spec(_).`ing as such
```erlang
-spec config_change(Changed :: [{Par :: atom(), Val :: term()}],
                    New :: [{Par :: atom(), Val :: term()}],
                    Removed :: [Par :: atom()])
      -> ok.
```
I am more busy `-spec(_).`ing as such
```erlang
-spec config_change(Changed, New, Removed) -> Result
      when Changed :: [{Par :: atom(), Val :: term()}],
           New :: [{Par :: atom(), Val :: term()}],
           Removed :: [Par :: atom()],
           Result :: ok.
```

On the other hand, `erlfmt` formats
```erlang
-spec config_change(Changed :: [{Par :: atom(), Val :: term()}],
                    New :: [{Par :: atom(), Val :: term()}],
                    Removed :: [Par :: atom()])
      -> ok.
```
as
```erlang
-spec config_change(
    Changed :: [{Par :: atom(), Val :: term()}],
    New :: [{Par :: atom(), Val :: term()}],
    Removed :: [Par :: atom()]
) -> ok.
```
I find its opinion to be a wrong one 😄. I think `-spec(_).` are one of the most powerful elements in maintenance and documentation and probably deserve special care (either that, or an option to not format them at all).
**Note**: this is not an issue, it's an opinion and a candidate for discussion if one's not already existed.

**Comment by paulo-ferraz-oliveira** [comment]
Another example:
```erlang
-spec handle_call(term(), {pid(), reference()}, state())
        -> {reply, Reply, state()} |
           {stop, unexpected_call, state()}
    when Reply :: ok | {error, {already_registered, pid()}}.
```
is getting formatted as
```erlang
-spec handle_call(term(), {pid(), reference()}, state()) ->
    {reply, Reply, state()} |
    {stop, unexpected_call, state()}
when
    Reply :: ok | {error, {already_registered, pid()}}.
```

**Comment by paulo-ferraz-oliveira** [comment]
After having fully evaluated (and accepting in many cases) `erlfmt`'s proposal in code changes, this is my biggest issue, at the moment, `-spec(_).`s.

**Comment by awalterschulze** [comment]
What do you find particularly wrong with this version of `erlfmt`ed code?
```erlang
-spec config_change(
    Changed :: [{Par :: atom(), Val :: term()}],
    New :: [{Par :: atom(), Val :: term()}],
    Removed :: [Par :: atom()]
) -> ok.

-spec handle_call(term(), {pid(), reference()}, state()) ->
    {reply, Reply, state()} |
    {stop, unexpected_call, state()}
when
    Reply :: ok | {error, {already_registered, pid()}}.
```

Personally I find them quite readable, so if you can point to the specific problems, it might help me understand better.

For example, is it:
1. alignment
2. The placement of `when` or
3. The breakup of the `|`

Thank you for reporting and thanks for taking the time to help me debug what exactly could be better.

**Comment by paulo-ferraz-oliveira** [comment]
I have no data or clear justification as to why something "feels" better than some other thing. We'd have to poll hundreds of people to get a clearer vision, I guess. Nonetheless, I'll try to reason on it.

```erlang
-spec config_change(
    Changed :: [{Par :: atom(), Val :: term()}],
    New :: [{Par :: atom(), Val :: term()}],
    Removed :: [Par :: atom()]
) -> ok.
```
Here, alignment seems off.

The same way you'd write 
```
fun(
    A,
    B,
    C
) ->
     ...
end
```
(I'm not sure this is how `erlfmt` would write it), having the `-spec(_).` there and now work _with that_ for alignment seems "strange".

How's this look?
```erlang
-spec config_change(
          Changed :: [{Par :: atom(), Val :: term()}],
          New :: [{Par :: atom(), Val :: term()}],
          Removed :: [Par :: atom()]
      ) -> ok.
```

I don't want to read my spec.s as if they were the header of a function. It's confusing enough as it is... 😄 


As for 
```erlang
-spec handle_call(term(), {pid(), reference()}, state()) ->
    {reply, Reply, state()} |
    {stop, unexpected_call, state()}
when
    Reply :: ok | {error, {already_registered, pid()}}.
```
why would the `when` be separate from the "guard"? Is it consistent with what `erlfmt` does for function declarations?

Something like
```erlang
-spec handle_call(
          term(),
          {pid(),
          reference()},
          state()
      ) -> {reply, Reply, state()}
         | {stop, unexpected_call, state()}
      when Reply :: ok | {error, {already_registered, pid()}}.
```
even if not to my full liking (I've expressed how I write my -spec.s in another Issue), seems better (again, I'm sorry, no data or other justification - they say beauty is in the eye of the beholder).

As for the placement of `->` (and trying to tie it all together) I guess this is how my mind reads code at a glance:
1. here's a -spec.
2. here's the function name
3. here's the parameters
4. here's the result value

If I have to search too hard for any of that stuff, it's tiring (especially when most of my day is spent reading code - written by me and others)...

which is why my latest preference goes toward:
```erlang
-spec function(Arg1, Arg2) -> Result
      when Arg1 :: type1(),
           Arg2 :: type2(),
           Result :: ok.
function(Arg1, Arg2) ->
    ...
    Result.
```
(what comes after `-spec(_).` replicates function headers, which also have no type; what comes after the when is "extra").

**Comment by awalterschulze** [comment]
Aha so here it seems again that is the placement of `when`
But this is what `erlfmt`ed code would look like:
```erlang
-spec function(Arg1, Arg2) -> Result when
    Arg1 :: type1(),
    Arg2 :: type2(),
    Result :: ok.
function(Arg1, Arg2) ->
    ...
    Result.
```

But here we have a big difference.
If you add newlines between your parameters, `erlfmt` will respect them and end up formatting
```erlang
-spec handle_call(
          term(),
          {pid(),
          reference()},
          state()
      ) -> {reply, Reply, state()}
         | {stop, unexpected_call, state()}
      when Reply :: ok | {error, {already_registered, pid()}}.
```
as
```erlang
-spec handle_call(
    term(),
    {pid(), reference()},
    state()
) ->
    {reply, Reply, state()} |
    {stop, unexpected_call, state()}
when
    Reply :: ok | {error, {already_registered, pid()}}.
```

I do think though that you can still read it as:

1. here's a -spec.
2. here's the function name
3. here's the parameters
4. here's the result value

But I get that it is hard to explain.
And yes it isn't possible (for us) to do a survey of 100s (even though we are probably half way to our first 100), but you are also a data point, so your opinion is still useful.
Thank you for engaging, we really appreciate it.

**Comment by paulo-ferraz-oliveira** [comment]
I'd take a look at `edoc` and probably some other doc. generation tools in the Erlang ecosystem and figure out what format _helps them best_. If I remember correctly `edoc` "prefers" it like so (produces more visually pleasant output, that is):
```erlang
-spec config_change(Changed, New, Removed) -> Result
      when Changed :: [{Par :: atom(), Val :: term()}],
           New :: [{Par :: atom(), Val :: term()}],
           Removed :: [Par :: atom()],
           Result :: ok.
```
(not looking at format here, but merely at the declaration of stuff with a `when`)

**Comment by michalmuskala** [comment]
My primary argument against formatting the specs as "floating" after `-spec` attribute is the `-callback` attribute. Since they use the same syntax, they should be formatted in exactly the same way, but formatting `-callback`s "floating" wastes a lot of horizontal space:
```erl
-callback handle_call(
              term(),
              {pid(),
              reference()},
              state()
          ) -> {reply, Reply, state()}
             | {stop, unexpected_call, state()}
          when Reply :: ok | {error, {already_registered, pid()}}.
```

Nesting things this deeply means we might need to break them up more often (since things that otherwise would fit, now won't) making the situation even worse. In particular for the variables appearing after `when` in a formatting like this we effectively decrease the width by 15% (10 spaces + `when` + a space after), current formatting "wastes" only 4% of space in this place.

**Comment by paulo-ferraz-oliveira** [comment]
[This is how](https://erlang.org/doc/man/gen_server.html#Module:handle_call-3) `:handle_call/3` is declared, in Erlang/OTP's docs.

And this is how I have it, usually, in my code:
```erlang
-callback handle_call(Request, From, State) -> Result
          when Request :: term()
             | From :: :: {pid(), reference()}
             | State :: state()
             | Result :: {reply, Reply, state()} | {stop, unexpected_call, state()}.
```
Were you to "waste less space" you could also do (shifting the `when` back, for consistency between `callback` and `spec`):
```erlang
-callback handle_call(Request, From, State) -> Result
    when Request :: term()
       | From :: :: {pid(), reference()}
       | State :: state()
       | Result :: {reply, Reply, state()} | {stop, unexpected_call, state()}.
```
or even
```erlang
-callback handle_call(Request, From, State) -> Result
    when Request :: term()
       | From :: :: {pid(), reference()}
       | State :: state()
       | Result :: {reply, Reply, state()}
                 | {stop, unexpected_call, state()}.
```

(at least for the cases that use `when` properly, since you can use it mixed with types in the declaration, but that's not nice 😄.

**Comment by michalmuskala** [comment]
Variables in `when` are separated with`,`, not `|`

Looking at the docs, this formatting seems closest to what's there would be something like (assuming `Types` is an edoc way to specify `when`):
```erl
-callback handle_call(Request, From, State) -> Result
when 
    Request :: term(),
    From :: :: {pid(), reference()},
    State :: state(),
    Result :: {reply, Reply, state()}
            | {stop, unexpected_call, state()}.
```

But I think it looks a bit weird with `-callback` and `when` next to each other like that.

Furthermore we definitely won't nest `Result` like that - floating the nested expression. The issue is that any changes to `Result` (e.g. renaming to `Response`) would result in re-indenting many lines. With that limitation removed, it would look like:
```erl
-callback handle_call(Request, From, State) -> Result
when 
    Request :: term(),
    From :: :: {pid(), reference()},
    State :: state(),
    Result :: 
        {reply, Reply, state()}
        | {stop, unexpected_call, state()}.
```

**Comment by paulo-ferraz-oliveira** [comment]
> Variables in when are separated with, not |

Right you are, I fixed it in my comment. Anyway, it wasn't about a detail.

**Comment by paulo-ferraz-oliveira** [comment]
> would result in re-indenting many lines

Good point.

**Comment by paulo-ferraz-oliveira** [comment]
Is there no way that the `|` could be "aligned" so that the alternatives start on the same column?, like so

```erlang
-callback handle_call(Request, From, State) -> Result
when 
    Request :: term(),
    From :: {pid(), reference()},
    State :: state(),
    Result :: 
        {reply, Reply, state()}
      | {stop, unexpected_call, state()}.
```

And on this note, why do you feel the `when` looks better as-is?

Is this very different?

```erlang
-callback handle_call(Request, From, State) -> Result
    when 
    Request :: term(),
    From :: {pid(), reference()},
    State :: state(),
    Result :: 
        {reply, Reply, state()}
      | {stop, unexpected_call, state()}.
```

**Comment by elbrujohalcon** [comment]
Another data point that I found while implementing AdRoll/rebar3_format#150 is that you need to contemplate specs and callbacks with multiple clauses, such as…

```erlang
-callback something(With, Multiple, Clauses) -> Result when With :: with, Multiple :: multiple, Clauses :: clauses, Result :: result;
                   (With, Multiple, Clauses) -> Result when With :: [with], Multiple :: [multiple], Clauses :: [clauses], Result :: [result];
                   ({With :: with}, {Multiple :: multiple}, {Clauses :: clauses}) -> {Result :: result}.

-spec something(With, Multiple, Clauses) -> Result when With :: with, Multiple :: multiple, Clauses :: clauses, Result :: result;
               (With, Multiple, Clauses) -> Result when With :: [with], Multiple :: [multiple], Clauses :: [clauses], Result :: [result];
               ({With :: with}, {Multiple :: multiple}, {Clauses :: clauses}) -> {Result :: result}.
```

**Comment by michalmuskala** [comment]
erlfmt would format those cases today as:
```erlang
-callback something
    (With, Multiple, Clauses) -> Result when
        With :: with, Multiple :: multiple, Clauses :: clauses, Result :: result;
    (With, Multiple, Clauses) -> Result when
        With :: [with], Multiple :: [multiple], Clauses :: [clauses], Result :: [result];
    ({With :: with}, {Multiple :: multiple}, {Clauses :: clauses}) -> {Result :: result}
```

**Comment by elbrujohalcon** [comment]
My editor (Sublime Text with [Sublime-Erlang](https://github.com/fjl/Sublime-Erlang) highlighting) doesn't like your choice, @michalmuskala :P

#### With `rebar3_format`'s `default_formatter`
![With `rebar3_format`](https://user-images.githubusercontent.com/93657/95309657-b9771e80-088b-11eb-9e73-1e85408b99ef.png)

#### With `erlfmt`
![With `erlfmt`](https://user-images.githubusercontent.com/93657/95309754-d57ac000-088b-11eb-9997-10a3b4e84a60.png)

Notice the change of color in `something`… Don't ask me what color that is, I'm colorblind, but… with `erlfmt` the function name is painted as _an atom_, while in the other case it's painted as a function name.

Of course, this is not an `erlfmt` issue… but I found it funny and wanted to share :)

**Comment by paulo-ferraz-oliveira** [comment]
This is no longer an issue, to me. Since I was the one that opened it, you're welcome to close it if there's no more work planned on top of it.

**Comment by paulo-ferraz-oliveira** [comment]
Any news on this?

**Comment by awalterschulze** [comment]
Not yet, still prioritizing fixing some issues.  Sorry for the wait.  Just to set some expectations we are juggling this with some other high priority projects at the moment, but we haven't forgotten about this.

**Comment by awalterschulze** [comment]
I think we have addressed this issue by changing how pipe is formatted to prefixes now, but to be honest I didn't reread the whole conversation.  If there is something I missed please comment and let me reopen.
