### ISSUE TITLE
Maps, records and tuples: removing spaces

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [WhatsApp/erlfmt#171]
I tend to format records like so
```erlang
#myrecord{ myvalue = 2 }
```

I tend to format maps like so
```erlang
#{ myvalue => 2 }
```

I tend to format tuples like so
```erlang
{myvalue, 2}
```

There's no real rationale for this placement of white space, but I'd like to understand the one behind `erlfmt` reason for removing initial and final white space for maps, when e.g. declared in a function. (haven't seen how it formats records, though, but suspect it's the same way - no spaces).

**Edit**: found a record 😄, and white space was stripped. I don't like it 😛

**Comment by awalterschulze** [comment]
Just to double check the tuple `{myvalue, 2}` you gave as example, seems to be formatted in the same way as erlfmt does today, I might be wrong.  Is this intentional?

**Comment by paulo-ferraz-oliveira** [comment]
No error there. `{myvalue, 2}` is how I'd write a tuple 😄. Just by looking at code, if there's no space after `{` I "know" it's a tuple; otherwise it might be a map or a record (I can just look at what's before `{` and "know") - it also makes searching easier, if there're rules. But this is one of those "less important discussions", for me.

**Comment by paulo-ferraz-oliveira** [comment]
I'm closing this, so focus can remain on stuff that matters. Do re-open if you feel the need to further discuss it.
