### ISSUE TITLE
`fun ()` with no space, in anonymous functions

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [WhatsApp/erlfmt#173]
Consider the following example:
```erlang
    MatchSpec = ets:fun2ms(fun (Combo) -> Combo#combo.delta =:= 0 end),
```
`erlfmt` changes it to:
```erlang
    MatchSpec = ets:fun2ms(fun(Combo) -> Combo#combo.delta =:= 0 end),
```
but `fun` is anonymous here (i.e. it's unnamed, which is not uncommon usage in Erlang) - I'm probably biased by some years using JavaScript and JSLint.

Quick search in OTP reveals the following number of occurrences (some might be in generated code, which would skew the metric):
* `fun(`: 25678
* `fun (`: 3208

Internally (our projects):
* `fun(`: 929
* `fun (`: 529

(not that big of a difference, but I can already see the issue being closed 😛)

**Comment by paulo-ferraz-oliveira** [comment]
This is very very _minor_, so... closing.

**Comment by michalmuskala** [comment]
I personally preferred the space as well, but after running the numbers on both OTP and our internal codebase, I couldn't really justify it.

**Comment by paulo-ferraz-oliveira** [comment]
I see formatting being adopted in one of three ways:
1. you start a new project, format it, nobody really cares about how it looks "now" because there's no base for comparison, thus everything is OK (and this might affect the way you start writing your code from now on),
2. you apply on an existing project and some will care because there were "style changes only",
3. you gradually apply it on an existing project, trying to make sure (no whitespace differences disabled) it's not very intrusive.

We all know there's always some resistance to change, right?
