### ISSUE TITLE
Formatting `type` introduced blank line

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [WhatsApp/erlfmt#175]
```erlang
-type special_type() :: {packet_dispatcher:type(), dec}
                      | {packet_dispatcher:type(), inc}.
-type metric_value() :: packet_dispatcher:value().
```
got formatted to:
```erlang
-type special_type() ::
    {packet_dispatcher:type(), dec} |
    {packet_dispatcher:type(), inc}.

-type metric_value() :: packet_dispatcher:value().
```

Is it to signal that the type is defined over multiple lines?

**Comment by paulo-ferraz-oliveira** [comment]
I found a similar situation with a comment (instead of code - where you have `metric_value` above) and formatting was applied with a new line too.

**Comment by paulo-ferraz-oliveira** [comment]
i.e.
```erlang
-type single_result() :: error_result()
                       | {ok, {single, json()}}.
 %% ^ this is the return type to use when you ask for a single user's info.
```
got formatted to
```erlang
-type single_result() ::
    error_result() |
    {ok, {single, json()}}.

 %% ^ this is the return type to use when you ask for a single user's info.
```

I'm aware this is a strange way to use comments, but still...

**Comment by awalterschulze** [comment]
erlfmt will honor newlines in certain places and assume you want a multiline formatting.

I guess the alternative would be for `erlfmt` to leave the left side of the `|` on the same line, which I do not think is what you want?

```erlang
-type special_type() :: {packet_dispatcher:type(), dec} |
    {packet_dispatcher:type(), inc}.
```

Or you could remove the newlines and get it all on one line today:
```erlang
-type special_type() :: {packet_dispatcher:type(), dec} | {packet_dispatcher:type(), inc}.
```

**Comment by paulo-ferraz-oliveira** [comment]
I didn't explain myself properly, but the title mentioned it. `erlfmt` is introducing a ~new~blank line where there was none (let me change that title for you):
* in my first comment, between two type declarations,
* in my third comment, between a type and a comment.

Thus my question: is it expected?

---

Also
```erlang
-type special_type() :: {packet_dispatcher:type(), dec}
                      | {packet_dispatcher:type(), inc}.
-type metric_value() :: packet_dispatcher:value().
```
is already to my liking (`|` to the left, aligned as "should").

This example follows the same thought pattern:
```erlang
-type single_result() :: error_result()
                       | {ok, {single, json()}}.
```

**Comment by awalterschulze** [comment]
Aha sorry for misunderstanding and thank you so much for clarifying.  This is very useful.

So yes, `erlfmt` adds an emptyline between multiline type declarations.
If you keep both on a single line, they won't get an empty line in between like so:
```erlang
-type special_type() :: {packet_dispatcher:type(), dec} | {packet_dispatcher:type(), inc}.
-type metric_value() :: packet_dispatcher:value().
```
What do you think about that?

About the comment below the type.
I don't believe that this is a comment style we would want to encourage to be widely used, if that makes sense?

Lets keep the pipe discussion to the pipe issue https://github.com/WhatsApp/erlfmt/issues/167
It will really help is to take the appropriate information into account when we are thinking about a specific issue.
Is it possible to go and mention the pipe parts there again?

**Comment by paulo-ferraz-oliveira** [comment]
> What do you think about that?

I guess it probably won't hurt to have a single blank line added, for readability. I just wanted to understand if it was expected behavior. Blank lines are the least of our concerns 😃  except if they're a bug 😄 

Closing. Thanks.

**Comment by awalterschulze** [comment]
Thank you for being so accommodating :D
