### ISSUE TITLE
Formatting `edoc` elements

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [WhatsApp/erlfmt#176]
I usually write `%% @private` between a function's `-spec(_).` and its declaration, like so:

```erlang
-spec add(A :: integer(), B :: integer()) -> integer().
%% @private
add(A, B) ->
```

`erlfmt` prefers it like
```erlang
-spec add(A :: integer(), B :: integer()) -> integer().
    %% @private
add(A, B) ->
```

OTP code has pretty much no occurrences of ` %% @private`, but some `%% @private`.

Should, generically speaking, `%% @` be an exception to "comments"?

**Comment by paulo-ferraz-oliveira** [comment]
Oh, it `%% @private` is before `-spec(_).` the "issue" doesn't happen.

**Comment by awalterschulze** [comment]
This seems similar to a problem we have discovered before https://github.com/WhatsApp/erlfmt/issues/135
I hope it is okay, if I close this and merge it in that issue.
