### ISSUE TITLE
rebar3: `rebar3 fmt` execution priority

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [WhatsApp/erlfmt#177]
I have the following in `rebar.config`:
```erlang
{erlfmt, [
    write,
    {files, "{src,include,test}/*.{hrl,erl}"}
]}.
```
I ran `erlfmt` and starting staging changes in Git, for further commit and push. The ones I don't like, I discard.

I saw that I wanted to redo formatting on a single file so I did `rebar3 fmt <file>`.

To my surprise all files were formatted again. Is this the expectation, or should `files` (from `rebar.config`) be ignored, if `<file>` is present in the CLI?

**Comment by elbrujohalcon** [comment]
I guess you need to use `rebar3 fmt --files <file>` instead.

**Comment by paulo-ferraz-oliveira** [comment]
> I guess you need to use `rebar3 fmt --files <file>` instead.

```===> Invalid option --files on task fmt```

In any case, whatever it is, the usage has to be respected, and probably CLI options have to overlap `rebar.config` ones (?)

**Comment by michalmuskala** [comment]
The interaction between CLI options and defaults set in `rebar.config` is something we definitely need to improve. We talked about this with @awalterschulze some time ago, but it didn't end up in any concrete issue. This might as well be it.

**Comment by awalterschulze** [comment]
Thank you for bringing this up.

How does rebar3 options get passed to erlfmt?

What are the options we should support?

This seems similar to https://github.com/WhatsApp/erlfmt/issues/141

**Comment by paulo-ferraz-oliveira** [comment]
> How does rebar3 options get passed to erlfmt?

It's options from `rebar.config`, but they're `erlfmt` options.

Stuff like
```erlang
{erlfmt, [
    write,
    {files, "{src,include,test}/*.{hrl,erl}"}
]}.
```

> This seems similar to #141

Related, yes.

I don't know all of which exist, but have seen (mostly) plugins allow for the same options in CLI and `rebar.config`.

So:
* CLI `--write` might be config `write`
* CLI `--out <folder>` might be config `{out, <folder>}`
* CLI `--verbose` might be config `verbose`
...

(the most "complex" one will probably be `files`). In any case (it might depend on your expectations) there has to be a rule over what overrides what (I've mostly seen CLI override `rebar.config`).

**Comment by michalmuskala** [comment]
We discussed this with @awalterschulze today.

The TL;DR for the plan is:
* files from CLI override files from config
* mode: write/check/... - CLI overrides
   * rebar3 fmt (with files + write in config), formats in place
   * rebar3 fmt --check (with files + write in config), checks
   * rebar3 fmt -o path (with files + write in config), -o wins and oputputs to path

**Comment by paulo-ferraz-oliveira** [comment]
Thanks for this.

@michalmuskala: are all the options mapped from `rebar.config` to CLI? (if not, are they going to be?)

**Comment by michalmuskala** [comment]
I believe they are already mapped fairly well:

|CLI | rebar.config
----|--
| --check | check
| --out path | {out, Path}
| --write | write
| --print-width X | {print_width, X}
| --require-pragma | require_pragma
| --insert-pragma | insert_pragma
| \<list of files> | {files, [\<list of files>]} 

cc @awalterschulze we also need to take care of `--insert-pragma` from CLI overriding `--require-pragma` in conifg.

**Comment by paulo-ferraz-oliveira** [comment]
Great. Is this supposed to go in the README? Or can we find it somewhere else, already?

**Comment by michalmuskala** [comment]
This is a good point. We should document the options in `rebar.config`, I don't think we have this anywhere explicitly today

**Comment by awalterschulze** [comment]
I think I will create a separate markdown file, with a link from the readme.

**Comment by awalterschulze** [comment]
The pull request now includes a document
https://github.com/WhatsApp/erlfmt/pull/196
