### ISSUE TITLE
ifdef: Empty line before `-endif`

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [WhatsApp/erlfmt#178]
It seems that before `-endif`, an empty line is being forced - I imagine it's because the previous function "closes".

For consistency (if it's not a bug) shouldn't the same be done for `-ifdef` (et al.) - add an empty line after it?

**Comment by paulo-ferraz-oliveira** [comment]
This seems to happen for `-else` too.

**Comment by awalterschulze** [comment]
Sorry to bother you, but could I ask for some examples, which I can then use to explain or find that we missed something?

**Comment by paulo-ferraz-oliveira** [comment]
No bother. Let me get that for you.

```erlang
-ifdef(TEST).
start(_StartType, _StartArgs) ->
    mylib_sup:start_link().

stop(_State) ->
    ok.
-endif().
```

gets formatted as (well I can't compile it now, but I remember the result):

```erlang
-ifdef(TEST).
start(_StartType, _StartArgs) ->
    mylib_sup:start_link().

stop(_State) ->
    ok.

-endif().
```
(there's a blank line there).

😞 
Oh, I just saw `erlfmt` is OTP 21+ :-) it didn't compile in an OTP 19 project and "crashed"...

**Comment by paulo-ferraz-oliveira** [comment]
> 😞
> Oh, I just saw erlfmt is OTP 21+ :-) it didn't compile in an OTP 19 project and "crashed"...

You can prevent such an issue by stating your intentions in `rebar.config` [like so](https://github.com/AdRoll/rebar3_format/blob/master/rebar.config#L17).

**Comment by awalterschulze** [comment]
Cool I'll try adding the minimum version.

**Comment by awalterschulze** [comment]
I have confirmed that a newline is added before `-endif`
This test fails.
```erlang
?assertSame(
        "-ifdef(TEST).\n"
        "start(_StartType, _StartArgs) ->\n"
        "    mylib_sup:start_link().\n"
        "\n"
        "stop(_State) ->\n"
        "    ok.\n"
        "-endif().\n"
    ).
```

This is unintentional and is a bug.
The newlines between `-ifdef` and `-endif` are supposed to be preserved.

**Comment by awalterschulze** [comment]
Thank you for reporting :D

**Comment by awalterschulze** [comment]
It seems to do with the fact that `-endif().` looks like a function call, instead of being a plain `endif`

This test seems:

```erlang
?assertSame(
        "-ifdef(TEST).\n"
        "start(_StartType, _StartArgs) ->\n"
        "    mylib_sup:start_link().\n"
        "\n"
        "stop(_State) ->\n"
        "    ok.\n"
        "-endif.\n"
    ).
```

**Comment by awalterschulze** [comment]
The same problem happens with `-else.` when we make it a call `-else().`

The ast node for `-endif().` and `-else().` seems to look like
```erlang
{exprs,#{dot => true, end_location => _,location => _},
           [{op,#{end_location =>_,location => _},
                '-',
                {call,#{end_location => _,location => _},
                      {atom,#{end_location => _,
                              location => _,
                              text => "else"},
                            else},
                      []}}]}
```

But it seems like this should have been parsed to be an attribute, like `-ifdef(TEST)` was.

When I pass a random parameter for example `-endif(test).`, it also seems to pass the test:
```erlang
?assertSame(
        "-ifdef(TEST).\n"
        "start(_StartType, _StartArgs) ->\n"
        "    mylib_sup:start_link().\n"
        "\n"
        "stop(_State) ->\n"
        "    ok.\n"
        "-endif(test).\n"
    ).
```

So to me this looks like a parsing error.

**Comment by paulo-ferraz-oliveira** [comment]
> So to me this looks like a parsing error.

[or it's just being ignored on purpose, since it doesn't have any practical effect]

OTP's open to PRs, though 😄

**Comment by awalterschulze** [comment]
We have updated our erlang parser and now the special case is recognized, so this issue should be fixed :)

**Comment by michalmuskala** [comment]
In OTP/standard toolchain this is handled during macro expansion, but we can't expand macros when parsing - otherwise we couldn't print macros back. We have a forked parser that handles some macros as first-class expressions - this was a case we were missing.
