### ISSUE TITLE
`when` in function header

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [WhatsApp/erlfmt#179]
```erlang
send_other_stats_for_item(StatsInfoContainer, Item, _Tags)
    when StatsInfoContainer =:= dynamic_eval ->
```
is getting formatted to
```erlang
send_other_stats_for_item(StatsInfoContainer, Item, _Tags) when
    StatsInfoContainer =:= dynamic_eval
->
```

I imagine that since a predefined column is overflow, `erlfmt` breaks the code.
What I question is:
1. whether it should not break `when` along with the guard also (?),
2. (maybe specific to this example), should `->` be found after the guard?

**Comment by awalterschulze** [comment]
We have thought about quite a few options regarding this specific case, see our formatting decision document:
https://github.com/WhatsApp/erlfmt/blob/master/doc/FormattingDecisionWhenMultilineGuards.md

I am going to close this issue for now, 
but if you have another option we can consider or disagree with our goals or our evaluation, please reopen.
