### ISSUE TITLE
Empty lines between function clauses

### ISSUE THREAD

**Issue by michalmuskala** [WhatsApp/erlfmt#18]
Today the formatter produces an empty line between functions and no empty lines between function clauses. Combined with keeping empty lines inside functions, this sometimes leads to code that is hard to read, for example:

```erl
parse_opts([version | _Rest], Name, _Files, _Config) ->
    {ok, Vsn} = application:get_key(erlfmt, vsn),

    io:format("~s version ~s\n", [Name, Vsn]),
    erlang:halt(0);
parse_opts([write | Rest], Name, Files, Config) ->
    parse_opts(Rest, Name, Files, Config#config{out = replace})
...
```

The solution would probably be to introduce extra empty lines. Elixir always has an empty line between clauses (unless they are all single-line) and an empty line between functions. This has a disadvantage of not clearly delineating boundaries between different functions.

My proposed approach would be to always introduce an empty line between clauses and 2 empty lines between functions. The empty line between clauses could be omitted if clauses are single-line.

**Comment by alanz** [comment]
One between clauses and two between functions sounds good to me.

In my personal code I often put a comment line across the page where between functions, to clearly delineate things. So

```erlang
foo() -> ok.

%% -----------------------------------------------------

baz([]) -> ok.

baz(....

```

**Comment by michalmuskala** [comment]
Yeah, that is pretty common with some "section dividers" something like:

```erl
%% public interface

foo() -> ok.

%% gen_server callbacks

handle_call(...) -> ok.

handle_cast(...) -> ...

```

We'll need to support that

**Comment by eproxus** [comment]
It is obviously a matter of personal taste, but I don't have a problem with white space inside functions. Granted, I never add them for small functions like the 3-line example here. I find that the indented function body provides a good visual distinction that the block continues in most cases.

In my opinion, a function should be so short you don't have to add white space block inside to make it clearer. If the tool adds an remove newlines in other places, why not inside function bodies as well?

**Comment by richcarl** [comment]
Personally, I absolutely hate it when there are empty lines between function clauses. It breaks up the function and can make me completely miss that there is another clause of the same function above or below it, unless I start to really look for semicolons. Even the weirdness of empty lines in the middle of clauses but not between them is preferable to thinking that you've seen the whole function when in fact you haven't.

**Comment by awalterschulze** [comment]
@michalmuskala and I have reviewed the proposal and decided not to go ahead with it.
This means empty lines won't be added between function clauses.
