### ISSUE TITLE
Receive: Receive...after formatting

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [WhatsApp/erlfmt#180]
[Erlang -- Expressions](https://erlang.org/doc/reference_manual/expressions.html) writes `receive...after` such as
```erlang
receive
    PatternN [when GuardSeqN] ->
        BodyN
after
    ExprT ->
        BodyT
end
```
`erlfmt` prefers
```erlang
receive
    PatternN [when GuardSeqN] ->
        BodyN
after ExprT -> BodyT
```

It seems to break the reading flow a bit (my mind is thinking "actions after two _tabs_"), for me (and maybe some of the consistency?).

FWIW, in Erlang/OTP, I found `erlfmt`'s choice only in test suites.

**Comment by elbrujohalcon** [comment]
FWIW, the OTP pretty printer prints that thing as…

```erlang
    receive
        PatternN when GuardSeqN -> BodyN after ExprT -> BodyT
    end.
```

…or with larger stuff that needs indentation…

```erlang
    receive
        {with, larger, stuff, that, needs, indentation}
            when this:happens() ->
            [with, larger, stuff, that, needs, indentation]
        after some:strangely(large, "after", thingy) ->
                  [with, larger, stuff, that, needs, indentation]
    end.
```

**Comment by elbrujohalcon** [comment]
Oh, and… stuff like this (which is totally valid BTW - ⚠️ don't do this at home, kids ⚠️ )…

```erlang
receive X -> X after begin io:format("Before: ~p~n", [calendar:universal_time()]), 2000 end -> io:format("After: ~p~n", [calendar:universal_time()]), calendar:universal_time() end.
```

…looks like this with `erlfmt`…
```erlang
    receive
        X -> X
    after begin
            io:format("Before: ~p~n", [calendar:universal_time()]),
            2000
        end ->
        io:format("After: ~p~n", [calendar:universal_time()]),
        calendar:universal_time()
    end.
```

…like this with the OTP pretty printer…
```erlang
    receive
        X -> X
        after begin
                  io:format("Before: ~p~n", [calendar:universal_time()]),
                  2000
              end ->
                  io:format("After: ~p~n", [calendar:universal_time()]),
                  calendar:universal_time()
    end.
```

I'm not sure which one is "prettier"

**Comment by paulo-ferraz-oliveira** [comment]
> very very deep indentation after `after`

I can understand this argument. 

And I can also agree that 

```erlang
receive
    PatternN [when GuardSeqN] ->
        BodyN
after ExprT ->
    BodyT
```

looks better than

```erlang
receive
    PatternN [when GuardSeqN] ->
        BodyN
after ExprT -> BodyT
```

(even though I explained stuff as best I could in the initial description, for consistency and reading flow).

**Comment by paulo-ferraz-oliveira** [comment]
This is no longer an issue, to me. Since I was the one that opened it, you're welcome to close it if there's no more work planned on top of it.

**Comment by awalterschulze** [comment]
We can make it so that the newline after the arrow is preserved, which means that this will be kept as is:

```erlang
receive
    PatternN when GuardSeqN ->
        BodyN
after ExprT ->
    BodyT
```

and this

```erlang
receive
    PatternN [when GuardSeqN] ->
        BodyN
after
    ExprT ->
        BodyT
end
```

will also be formatted to the first one.
