### ISSUE TITLE
Maps: Curious formatting of alternatives in type spec for map field

### ISSUE THREAD

**Issue by ehamberg** [WhatsApp/erlfmt#181]
(erlfmt 0.7)

The following type spec for a map argument has a `name` field with three alternative types, but erlfmt only indents the first alternative:

```erlang
-spec child_spec(#{
    name =>
        {local, Name :: atom()} |
    {global, GlobalName :: any()} |
    {via, Module :: atom(), ViaName :: any()},
    another_field => atom()
}) -> supervisor:child_spec().
```

If I join all the four lines to make it `name => {local, Name :: atom()} | {global, GlobalName :: any()} | {via, Module :: atom(), ViaName :: any()}` and reformat, it splits that line, puts the first alternative on the first line and the rest on new lines – but without indentation:

```erlang
-spec child_spec(#{
    name => {local, Name :: atom()} |
    {global, GlobalName :: any()} |
    {via, Module :: atom(), ViaName :: any()},
    another_field => atom()
}) -> supervisor:child_spec().
```

I'm not sure what the correct behaviour here would be (but the first case above seems wrong).

Maybe something like this makes sense when the cases need to be split over multiple lines?

```erlang
-spec child_spec(#{
    name =>
        {local, Name :: atom()} |
        {global, GlobalName :: any()} |
        {via, Module :: atom(), ViaName :: any()},
    another_field => atom()
}) -> supervisor:child_spec().
```

**Comment by michalmuskala** [comment]
This definitely looks like a bug. Thank you for the report
