### ISSUE TITLE
Macro parens

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [WhatsApp/erlfmt#190]
```erlang
-define(REPORT_INTERVAL, (timer:seconds(5))).
```
doesn't get formatted.

Should you consider removing the parens as so:
```erlang
-define(REPORT_INTERVAL, timer:seconds(5)).
```
?

**Comment by awalterschulze** [comment]
We do not remove parens, as this sometimes causes bugs.
I remember @michalmuskala found a good example once.

It seems it does get formatted though.
I tried
```erlang
-define(REPORT_INTERVAL, ( timer:seconds(5))).
```
and it formatted to
```erlang
-define(REPORT_INTERVAL, (timer:seconds(5))).
```

Is it okay if we close this issue or did I miss what you were trying to say?

**Comment by michalmuskala** [comment]
Yes, erlfmt does not touch parentheses precisely because interactions with macros can be tricky. In particular consider the following:
```erl
-define(COMPUTE(X, Y), (X) * (Y)).
-define(COMPUTE2(X, Y), X * Y).

?COMPUTE(1 + 2, 3 + 4).
% expands to 
(1 + 2) * (3 + 4) = 21.

?COMPUTE2(1 + 2, 3 + 4).
% expands to 
1 + 2 * 3 + 4 = 11.
```

The outer parentheses can also change the meaning:
```erl
-define(COND(X, Y), (X orelse Y)).
-define(COND2(X, Y), X orelse Y).

false andalso ?COND(false, true).
% expands to 
false andalso (false orelse true) == false.

false andalso ?COND2(false, true).
% expands to 
false andalso false orelse true == true.
```

**Comment by paulo-ferraz-oliveira** [comment]
> The outer parentheses can also change the meaning:

Right you are; nice one. Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
I see @michalmuskala already [mentioned it here](https://github.com/AdRoll/rebar3_format/issues/74). Since my use case was very simple (as you can see from the example I posted) I didn't think of other consequences. I guess `rebar3_format` will probably fix it too.
