### ISSUE TITLE
...formatter result not equivalent. Please report this bug.

### ISSUE THREAD

**Issue by lukebakken** [WhatsApp/erlfmt#193]
Hello!

Thanks for the excellent project. I thought I'd run `erlfmt` on some code I'm updating:

https://github.com/rabbitmq/rabbitmq-common/blob/lrb-update-supervisor/src/supervisor2.erl

Here is the output I get:

```
(23.1)lbakken@shostakovich ~/development/WhatsApp/erlfmt (master=)
$ /home/lbakken/development/WhatsApp/erlfmt/_build/release/bin/erlfmt --write ~/development/rabbitmq/umbrella/deps/rabbit_common/src/supervisor2.erl 
/home/lbakken/development/rabbitmq/umbrella/deps/rabbit_common/src/supervisor2.erl: formatter result not equivalent. Please report this bug.

'|'

'::'
```

Let me know if you'd like more information, or if there is something I should test. Thanks!

**Comment by awalterschulze** [comment]
Thank you for trying it and reporting.  This was a mistake I made when switching pipes to the left hand side.
The pull request should fix it.

**Comment by lukebakken** [comment]
I have confirmed that this is fixed. Thank you!

**Comment by awalterschulze** [comment]
Thank you for confirming :) That is very helpful.

**Comment by lukebakken** [comment]
I don't suppose you or anyone you work with have a vim configuration that follows `erlfmt`? I've noticed that the stock Erlang formatter for vim differs quite a bit.

**Comment by awalterschulze** [comment]
I do not think so, I suspect it will take some time for one to emerge from our side, even though it is inevitable.

If you make one though, even if it just a gist, we will add it to our integrations section https://github.com/WhatsApp/erlfmt#integrations
