### ISSUE TITLE
Revisit placement of when

### ISSUE THREAD

**Issue by michalmuskala** [WhatsApp/erlfmt#20]
The general decision was for `when` to be placed either inline (when the guard is single-line) or on a new line doubly-indented. This worked well, except for the case of extremely small functions and multiline guards (for example, because of a comment):

```erl
bar(X)
        when is_tuple(X);
             % some comment
             is_list(X) ->
    ...
```

because of this, I decided to allow "floating" guards. With that change, the example above would look like this:

```erl
bar(X) when is_tuple(X);
            % some comment
            is_list(X) ->
    ...
```

Which looks much better, but has the unfortunate effect of "floating" guards that need to be moved when the function name changes - this is generally something we'd really want to avoid.

Some possible solutions are:
* don't indent `when`. This creates relatively little differentiation between guards and body of the function
```erl
bar(X)
when is_tuple(X);
     % some comment
     is_list(X) ->
    ...
```

* indent `when` half the indentation - this is better, but rather awkward - we don't use half-indentation anywhere else
```erl
bar(X)
  when is_tuple(X);
       % some comment
       is_list(X) ->
    ...
```

* indent `when` full indentation - this is good in for multiline guards, but fails the guard-body distinction check when guard is on a separate line, but single-line
```erl
bar(Some, Very, Long, Arguments)
    when is_tuple(X); is_list(X) ->
    ...
```

* treat `when` and `->` as a sort-of parenthesis - this preserves clarity, but has relatively low current usage
```erl
bar(X) when 
    is_tuple(X);
    % some comment
    is_list(X) 
->
    ...
```

**Comment by awalterschulze** [comment]
I really like:
```
bar(X) when 
    is_tuple(X);
    % some comment
    is_list(X) 
->
    ...
```
and at least closely matches how a few people format `forall` clauses in Coq.
Sorry `when` always make me think of dependent types.

**Comment by richcarl** [comment]
It's more important I think to make the separation clear between guard and body. Renaming a function is relatively unusual, so the floating solution seems superior.

**Comment by emtenet** [comment]
Excited to come across `erlfmt` having been a recent convert to `elm-format`.
Whilst testing `erlfmt` on some of my code I came across clauses like (as formatted by `erlfmt`):
```erlang
request_get_version(N, <<A, $., Rest/binary>>, Front) when ?IS_DIGIT(A) ->
    Body;
request_get_version(N, <<A, B, $., Rest/binary>>, Front) when ?IS_DIGIT(A), ?IS_DIGIT(B) ->
    Body;
request_get_version(N, <<A, B, C, $., Rest/binary>>, Front)
        when ?IS_DIGIT(A), ?IS_DIGIT(B), ?IS_DIGIT(C) ->
   Body;
```
To me, a "respect original format" option is more important than the actual formatting choice. For example, I would like to be able to choose to have guards on a new line even when they would fit on a single line. i.e.:
```erlang
request_get_version(N, <<A, $., Rest/binary>>, Front)
        when ?IS_DIGIT(A) ->
    Body;
request_get_version(N, <<A, B, $., Rest/binary>>, Front)
        when ?IS_DIGIT(A), ?IS_DIGIT(B) ->
    Body;
request_get_version(N, <<A, B, C, $., Rest/binary>>, Front)
        when ?IS_DIGIT(A), ?IS_DIGIT(B), ?IS_DIGIT(C) ->
   Body;
```

**Comment by awalterschulze** [comment]
Reopening as this still requires a reply.  I will create a formatting decision document explaining our thinking and link it here.

**Comment by awalterschulze** [comment]
We have created a formatting decision document explaining our thoughts
https://github.com/WhatsApp/erlfmt/blob/master/doc/FormattingDecisionWhenMultilineGuards.md

@emtenet I hope the new changed formatting from version 0.2.0 is acceptable and we hope given that, we don't need more formatting choices.  It was a great idea, but after more consideration we remembered that even though preserving newlines is sometimes useful, we would still like to avoid to use it to switch between even more different styles of formatting, since then the team becomes occupied with what code looks like, instead of what it does again, which is what this tool is supposed to help solve.

Thanks again for the great idea and keep them coming.

**Comment by awalterschulze** [comment]
@richcarl we have made it clear that "It's more important I think to make the separation clear between guard and body.", I hope the formatting decision document https://github.com/WhatsApp/erlfmt/blob/master/doc/FormattingDecisionWhenMultilineGuards.md addresses why we chose not to go floating guards.
