### ISSUE TITLE
Formatting an escript may disable emulator directives

### ISSUE THREAD

**Issue by ergl** [WhatsApp/erlfmt#205]
Consider the following script, which simply prints the cookie of the node (`my_cookie`)

```erlang
#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -sname foo -setcookie my_cookie

main(_) ->
    io:format("My cookie: ~s~n", [erlang:get_cookie()]).
```

After being formatted with `erlfmt` (version `0.7.0`), a blank line will be inserted between the first and second lines, and as such, the emulator arguments will be ignored. As such, the script won't start with `smp`, and the cookie will be `nocookie`. 

```erlang
#!/usr/bin/env escript

%% -*- erlang -*-
%%! -smp enable -sname foo -setcookie my_cookie

main(_) ->
    io:format("My cookie: ~s~n", [erlang:get_cookie()]).
```

From the [escript docs](https://erlang.org/doc/man/escript.html): 

> On the third line (or second line depending on the presence of the Emacs directive), arguments can be specified to the emulator

As such, the emulator directive line needs to _always_ be the second or third line of the escript file for it to be effective.

Bear in mind that if we remove the Emacs directive from the original script, the formatted version still works, because the blank line leaves the emulator directive on the 3rd line:

```erlang
#!/usr/bin/env escript

%%! -smp enable -sname foo -setcookie my_cookie

main(_) ->
    io:format("My cookie: ~s~n", [erlang:get_cookie()]).
```

**Comment by awalterschulze** [comment]
Thank you for reporting.  I will take a look at how to fix this in erlfmt.
