### ISSUE TITLE
Ability to exclude files

### ISSUE THREAD

**Issue by mheiber** [WhatsApp/erlfmt#208]
erlfmt currently accepts a `files` option to pass files or globs for erlmft to check.

We'd also find it helpful to have an `excludes` option: `{excludes, ["glob1", "glob2"]}` to avoid checking certain files.

Thanks for considering this feature request, I appreciate your work!

**Comment by awalterschulze** [comment]
I think erlfmt itself can also benefit from this feature to exclude `src/erlfmt_parse.erl`

Does `prettier` have a flag for this, as we have been mostly copying their flag names?

**Comment by awalterschulze** [comment]
We already have a rebar.config, so I would like to avoid another config file.
But we can add the flag `--ignore-path` and then that can be configured in the rebar.config
`{ignore_path, [pattern1, pattern2]}`

**Comment by paulo-ferraz-oliveira** [comment]
I gave you the link because you asked about the option name. :) I don't want config. another file either...
I'd call it `ignore` simply because you can choose to ignore a single file and not a bunch of them.

**Comment by awalterschulze** [comment]
I also think `ignore` is a better name, but this would then be the first parameter not consistent with prettier's parameter names and can mabye maybe maybe be confused with the ignore default value for pragma, so lets rather stick with the consistency with priettier's parameters.

**Comment by michalmuskala** [comment]
I think `ignore` makes more sense. `--ignore-path` in prettier points to a file containing ignore rules, so it seems like an entirely different option

**Comment by awalterschulze** [comment]
Aha my bad, great point.  I misread :(

Then how about we make sure there is no confusion and name it `exclude_files`

**Comment by michalmuskala** [comment]
I like `exclude_files`
