### ISSUE TITLE
Empty lines between preprocessor directives

### ISSUE THREAD

**Issue by ntalfer** [WhatsApp/erlfmt#21]
Hi Michal

Thanks a lot for the great work so far!

Let's take this file, not yet formatted:

```
-module(foo).
-inlude("foo.hrl").
-inlude("bar.hrl").
-export([foo/0]).
-export([bar/0]).
-define(FOO, "foo").
-define(BAR, "bar").
foo() -> ?FOO.
bar() -> ?BAR.
```
After formating, it becomes:

```
-module(foo).

-inlude("foo.hrl").

-inlude("bar.hrl").

-export([foo/0]).

-export([bar/0]).

-define(FOO, "foo").

-define(BAR, "bar").

foo() -> ?FOO.

bar() -> ?BAR.
```

It would be great to include an empty line only if the next directive is different, in order to group similar directives. This would produce the following output which I find nicer. But it's a matter of taste. ;)

```
-module(foo).

-inlude("foo.hrl").
-inlude("bar.hrl").

-export([foo/0]).
-export([bar/0]).

-define(FOO, "foo").
-define(BAR, "bar").

foo() -> ?FOO.

bar() -> ?BAR.
```
What do you think?

Nicolas

**Comment by michalmuskala** [comment]
Yes, I agree. The choice right now is simple & conservative, but it doesn't always result in the best looking code. I wonder, though, what should be done here if we choose to go for double newline between functions. Should it also be double newline between attributes? Or should it stay single?

**Comment by richcarl** [comment]
Please, not double newlines as default, neither between functions nor attributes.

**Comment by ntalfer** [comment]
Michal, I assume you refer to https://github.com/WhatsApp/erlfmt/issues/18

Elixir formatter has included empty lines between function clauses. 
Like @richcarl , I don't really like it, either in elixir or erlang, but I'm fine with it. 

Given the fact that you develop a non-configurable formatter, you'll always have people unhappy with the choices made.

Yet I think my proposal to group similar module attributes is something that makes sense for everyone.

**Comment by eproxus** [comment]
If it should be non-configurable, I would say that based on experience grouping function clauses is the by far used by the majority of Erlang code (haven't gathered any real stats in this, of course).

My vote goes for no newline between clauses and one newline between functions / groups of things (exports etc). And I would prefer to group similar directives without newlines as well.
