### ISSUE TITLE
Case: Compact first clauses

### ISSUE THREAD

**Issue by awalterschulze** [WhatsApp/erlfmt#210]
@rvirding proposed a new rule for formatting case statements.
He proposes keeping the single line clauses that follow “the rules” as single line until the first one that doesn’t. It will preserve clarity and not create too many very short lines.

Currently we format all clauses as single line, if they are all single line
```erlang
f(H) ->
    case H of
        head1 -> body1;
        head2 -> body2;
        head3 -> body3
    end.
```

If one is multiline, then all become multiline:
```erlang
f(H) ->
    case H of
        head1 ->
            body1;
        head2 ->
            multiline,
            body2;
        head3 ->
            body3
    end.
```

Robert's rule would format it, so that all clauses are single line, until we find a multiline clause and then all are multiline:

```erlang
f(H) ->
    case H of
        head1 -> body1;
        head2 ->
            multiline,
            body2;
        head3 ->
            body3
    end.
```

Here is an extraction from erlfmt itself, that is currently formatted as:
```erlang
-spec resolve_parsed(parsed(), parsed()) -> parsed().
resolve_parsed(PreferParsed, DefaultParsed) ->
    case {PreferParsed, DefaultParsed} of
        {{error, _} = Error, _} ->
            Error;
        {_, {error, _} = Error} ->
            Error;
        {help, _} ->
            help;
        {_, help} ->
            help;
        {version, _} ->
            version;
        {_, version} ->
            version;
        {{format, PreferFiles, PreferConfig}, {format, DefaultFiles, DefaultConfig}} ->
            {format, resolve_files(PreferFiles, DefaultFiles),
                resolve_config(PreferConfig, DefaultConfig)}
    end.
```

With Robert's new rule it would be formatted as:
```erlang
case {PreferParsed, DefaultParsed} of
    {{error, _} = Error, _} -> Error;
    {_, {error, _} = Error} -> Error;
    {help, _} -> help;
    {_, help} -> help;
    {version, _} -> version;
    {_, version} -> version;
    {{format, PreferFiles, PreferConfig}, {format, DefaultFiles, DefaultConfig}} ->
        {format, resolve_files(PreferFiles, DefaultFiles),
            resolve_config(PreferConfig, DefaultConfig)}
end.
```

**Comment by awalterschulze** [comment]
A problem is that this case would not cover the almost always single line error case:

```erlang
case Example of
   a_thing ->
          multline_stuff,
          more_multiline;
   _ ->
          error
end
```

Do we want this to also be single line?

**Comment by michalmuskala** [comment]
Unfortunately because the algorithm for formatting we're using is greedy and runs left-to-right making decisions based on right side (or something that is present below) is generally very complex. I think from that perspective implementing a rule "last clauses can be single-line" might be very complex if not impossible with the current algorithm.

Either way, I'm not a big fan of what this issue proposes. I don't think it improves readability - the primary goal is to save on vertical space in some situations. And while it could be beneficial in certain scenarios, I don't think it's worth the increased complexity in the rules erlfmt follows  - "either all single-line or all multi-line" is a very simple idea to explain.

**Comment by awalterschulze** [comment]
I guess it is hard and sometimes impossible to create a nice formatting for all cases, so maybe we should opt for predictability for the user and keep the current formatting of "either all single-line or all multi-line" and close this issue.

**Comment by awalterschulze** [comment]
I hope it makes sense to close this as `won't fix`.
