### ISSUE TITLE
erlfmt -w bumps mtime of all files it checks

### ISSUE THREAD

**Issue by kvelicka** [WhatsApp/erlfmt#231]
My employer uses a custom build system for Erlang which can be very fast for incremental builds because it only recompiles files that have changed. However, I've noticed that the incremental aspect of it got broken once we started using `erlfmt` and periodically ran `erlfmt -w` because it modifies (presumably overwrites) any files that are checked.

Is there some fundamental reason why `erlfmt` writes to files that don't require any formatting changes? If not, I'd be happy to have a go at making a patch for this myself. In that case please let me know if there's some particular approach that the maintainers would prefer me to take here.

**Comment by michalmuskala** [comment]
I agree a behaviour where we don't touch unchanged files would be better.

The way erlfmt works right now is that it just formats all the files and writes them. To do this, we'd need to track the original and compare if changed. It would be a fair bit of changes
