### ISSUE TITLE
[OOT] [Q] Why WhatsApp developers not using Go

### ISSUE THREAD

**Issue by batara666** [WhatsApp/erlfmt#250]

**Comment by awalterschulze** [comment]
I have personal opinions why I think erlang was and still is a good decision, but I am not equipped to answer this for WhatsApp in an official manner. Sorry, I hope that makes sense.
I think there are some great videos on YouTube about WhatsApp and Erlang that I would recommend you watch.

**Comment by batara666** [comment]
yeah, erlang use on whatsapp has been amaze me and makes me to use erlang technology (Elixir), but I ended to be Go user

**Comment by awalterschulze** [comment]
I assume that is because of Go job market being so big or other reason?
