### ISSUE TITLE
Parser can't handle macro in module-qualifier within types

### ISSUE THREAD

**Issue by gomoripeti** [WhatsApp/erlfmt#253]
The below examples don't parse and it feels like it would be easy to fix (but there might be some reason why macros are not allowed in these positions)
```
-spec ?MODULE:f() -> t().
-spec f() -> ?MODULE:t().
```
```
-spec mod:?FOO() -> t().
-spec f() -> mod:?FOO().
```

**Comment by awalterschulze** [comment]
Thank you so much for reporting.  A fix is landing soon and will ship with a new release.

**Comment by gomoripeti** [comment]
that was quick, thank you :)
