### ISSUE TITLE
Doesn't seem to format -spec

### ISSUE THREAD

**Issue by lehoff** [WhatsApp/erlfmt#257]
I keep getting this one:
```
src/endpoints_residency.erl:134: Line too long (104 > 100)
```

The line in question:
```
-spec delete_residency_region_customers(Residency :: binary(), Region :: binary(), [CID :: binary()]) ->
```

Other lines that are too long are reformatted just fine.

**Comment by awalterschulze** [comment]
Thank you for reporting.
Could you maybe provide the whole `-spec` form, up until the dot `.` ?

**Comment by awalterschulze** [comment]
I tried it with `ok.`, see 

?assertSame(
        "-spec delete_residency_region_customers(Residency :: binary(), Region :: binary(), [CID :: binary()]) ->\n"
        "    ok.\n"
    ),

But this formats to

```
-spec delete_residency_region_customers(
    Residency :: binary(),
    Region :: binary(),
    [CID :: binary()]
) -> ok.
```

which version of erlfmt are you using?

**Comment by awalterschulze** [comment]
Interesting, I get
```
-spec delete_residency_region_customers(
    Residency :: binary(),
    Region :: binary(),
    [CID :: binary()]
) -> ok | {error, any()}.
```

**Comment by awalterschulze** [comment]
But when I format a file, that contains this function, then it does not get formatted.
Ah that is because our test cases still have a default print width of 80, instead of 100,
so 
```
?assertSame(
        "-spec delete_residency_region_customers(Residency :: binary(), Region :: binary(), [CID :: binary()]) ->\n"
        "    ok | {error, any()}.\n",
        100
    ), 
```
is a test that is passing, even though it is 105 columns wide.

**Comment by awalterschulze** [comment]
There are many cases where erlfmt does not break a line that is too long, you can see this by running erlfmt on itself:

```
$ _build/release/bin/erlfmt --verbose -w
src/erlfmt_cli.erl:45: Line too long (102 > 100)
src/erlfmt_scan.erl:345: Line too long (104 > 100)
src/erlfmt_cli.erl:95: Line too long (101 > 100)
src/erlfmt_cli.erl:131: Line too long (111 > 100)
src/erlfmt_cli.erl:173: Line too long (101 > 100)
src/erlfmt.erl:403: Line too long (101 > 100)
src/erlfmt_algebra.erl:93: Line too long (106 > 100)
src/erlfmt_algebra.erl:103: Line too long (110 > 100)
src/erlfmt_algebra.erl:113: Line too long (119 > 100)
src/erlfmt_algebra.erl:134: Line too long (119 > 100)
src/erlfmt_algebra.erl:167: Line too long (113 > 100)
src/erlfmt_algebra.erl:216: Line too long (129 > 100)
# For example, this is a comment which is not broken
src/erlfmt_algebra.erl:391: Line too long (132 > 100)
src/erlfmt_algebra.erl:439: Line too long (101 > 100)
test/erlfmt_format_SUITE.erl:645: Line too long (124 > 100)
test/erlfmt_format_SUITE.erl:746: Line too long (103 > 100)
test/erlfmt_format_SUITE.erl:1189: Line too long (110 > 100)
test/erlfmt_format_SUITE.erl:1436: Line too long (104 > 100)
test/erlfmt_format_SUITE.erl:2290: Line too long (116 > 100)
test/erlfmt_format_SUITE.erl:2296: Line too long (124 > 100)
test/erlfmt_format_SUITE.erl:2348: Line too long (101 > 100)
test/erlfmt_format_SUITE.erl:2377: Line too long (112 > 100)
test/erlfmt_format_SUITE.erl:2440: Line too long (116 > 100)
test/erlfmt_SUITE.erl:600: Line too long (101 > 100)
test/erlfmt_SUITE.erl:1378: Line too long (107 > 100)
```
The algorithm can only break on places where we have added possible breaks.
If it has greedily already laid out a part without breaking, it cannot backtrack to suddenly create breaks.
The maximum length is best effort.

I hope that makes sense.

**Comment by awalterschulze** [comment]
If you do want this to break, simply over several lines, you can add a newline after the open paren `(` and it will preserve the new line and format the whole spec across several lines.

**Comment by awalterschulze** [comment]
Some history: we did try to adopt a non greedy algorithm first, but this resulted in exponential complexity and practically slowed down the formatter to unusable speeds.

**Comment by awalterschulze** [comment]
Going to close this, I hope it makes sense.

**Comment by lehoff** [comment]
It makes sense - just wanted to give feedback on a problem as the real world is crazier than what one can think of in a test case ;-)
I'll use the work-around.
