### ISSUE TITLE
Option to use tabs as whitespace

### ISSUE THREAD

**Issue by kvelicka** [WhatsApp/erlfmt#26]
Hi,

I'm a big fan of the ideology of this project (i.e. sensible defaults, little configuration) but one thing sticks out for the codebase I work on - it's been using tabs for indentation since its inception, so running `erlfmt` reformats basically everything.

So, I'm wondering whether `erlfmt` is open to allowing users to configure what type of whitespace to use in their project. In the case you're not, I think it would be helpful to at least mention that explicitly in the readme or documentation - currently the words `tab`/`tabs` gets no hits in the `erlfmt` git repo.

**Comment by michalmuskala** [comment]
Hi @kvelicka!

As it stands right now this is not something I'm planning to make configurable.

I agree, though, that there needs to be some explanation of the decisions erlfmt makes. I'll add a style guide to the repo that outlines the style that erlfmt adheres to.

**Comment by kvelicka** [comment]
Thanks for the quick reply! It's a bit of a shame, but that's the cost of uniformity.. I'll keep the ticket open for the style guide bit you mentioned.
