### ISSUE TITLE
Parser crashes on bad record

### ISSUE THREAD

**Issue by gomoripeti** [WhatsApp/erlfmt#260]
The parser crashes on a bad record while it wants to emit a meaningful error

```
1> erlfmt:read_nodes_string("nofile","-record(r, {12}).").
** exception error: bad argument
     in function  erl_anno:anno_info/1
        called as erl_anno:anno_info(#{end_location => {1,15},location => {1,13},text => "12"})
     in call from erlfmt_parse:ret_err/2 (/Users/ext.pgomori/git/erlfmt/src/erlfmt_parse.yrl, line 1059)
     in call from erlfmt_parse:record_tuple/1 (/Users/ext.pgomori/git/erlfmt/src/erlfmt_parse.yrl, line 1042)
     in call from erlfmt_parse:build_attribute/3 (/Users/ext.pgomori/git/erlfmt/src/erlfmt_parse.yrl, line 1035)
```

I think there is a mixup (maybe just leftover from `erl_parse`) between `erl_anno:anno()` and `erlfmt_scan:anno()`
Probably this should also be `erlfmt_scan:token()` https://github.com/WhatsApp/erlfmt/blob/master/src/erlfmt_parse.yrl#L967

Additionally `erlfmt_parse:record_tuple/1` seems to prevent parsing a macro as a record field, eg
```
-define(F1, field1).
-record(r, {?F1}).
```

**Comment by awalterschulze** [comment]
Thank you for reporting.  We will look into it asap.
