### ISSUE TITLE
Add special mode which would do reformat regardless of line width

### ISSUE THREAD

**Issue by iilyak** [WhatsApp/erlfmt#292]
We are evaluating erlfmt for CouchDB codebase [here](https://github.com/apache/couchdb/pull/3568).

Currently erlfmt respects original formatting most of the time if the line fits the configured line width.
During initial conversion it would be useful to have a mode where erlfmt always reformat lines. 

Here is how it could be used.

1. use erlfmt to reformat all code
2. commit 
3. use special erlfmt mode to force reformatting even if the line fits
4. use `git add -p` to selectively commit chunks where it makes sense

**Comment by awalterschulze** [comment]
I don't know if I understand.

currently erlfmt always reformats, even if the line fits.
When the line doesn't fit, is when the formatting differs more from the original, but it doesn't mean that when it fits, that it is not formatted.

**Comment by iilyak** [comment]
I've probably misunderstood how it works then.

I've noticed that sometimes the behaviour is different. So I've made an assumption that it is based on the fit to the line width. I am happy to close the issue.

[here](https://github.com/apache/couchdb/pull/3568/files/4b5449510c2d13865c2bbd24067ed4f97bec1122#diff-a8cd08c496b1621f5f9ddeb3bf001005c1ebaf7db81432fde01f7624a35ea8dcR530)
```
?LOG_NOTICE(
     #{
     ...
     },
    #{domain => [chttpd_access_log]}
),
```

[here](https://github.com/apache/couchdb/pull/3568/files/4b5449510c2d13865c2bbd24067ed4f97bec1122#diff-aef0d33630535b13f4bee549d7010ee471d3c5df0dbd72bb6b7ecc5003549571R163)
```
?LOG_NOTICE(#{
...
}),
```

**Comment by awalterschulze** [comment]
Unfortunately the links didn't work, probably too big a diff for chrome to handle.
But I am going to guess and say maybe it has something to do with https://github.com/whatsapp/erlfmt#manual-interventions
How far am I off?

**Comment by awalterschulze** [comment]
@iilyak I looked at the links, but I still do not understand.  Maybe I will try again:

Here the `#{}` is grabbed closer to the `(`, since it is a single parameter.

```erlang
?LOG_NOTICE(#{
...
}),
```

But here we have two parameters, so the parenthesis, do not grab.

```erlang
?LOG_NOTICE(
     #{
     ...
     },
     #{domain => [chttpd_access_log]}
),
```

Is this what you were asking about?
