### ISSUE TITLE
A certain line where print_width is not respected

### ISSUE THREAD

**Issue by eproxus** [WhatsApp/erlfmt#301]
There's a bug where `{print_width, 80}` is not respected when formatting the following module (doesn't compile because I tried to make a minimal example):

```erlang
-module(hello).

% API
-export([start/2]).

start(_Opts, Routes) ->
    App = foo,
    AllRoutes = routes(App, [{"/hello", hello_static, #{app => hello}}|Routes]).
```

Line 8 is exactly 80 characters wide.

## Actual outcome

```erlang
-module(hello).

% API
-export([start/2]).

start(_Opts, Routes) ->
    App = foo,
    AllRoutes = routes(App, [{"/hello", hello_static, #{app => hello}} | Routes]). % width = 82
```

Line 8 is now 82 characters wide.

## Expected outcome

```erlang
-module(hello).

% API
-export([start/2]).

start(_Opts, Routes) ->
    App = foo,
    AllRoutes = routes(App, [
        {"/hello", hello_static, #{app => hello}}
        | Routes
    ]).
```

## Additional Information

If I set the width to 79 it works, but of course changes formatting elsewhere in other files.

The bug happens when running `rebar3 fmt --write src/hello.erl` and also via `rebar3_formatter`.

**Comment by awalterschulze** [comment]
Unfortunately this is a side effect of the underlying algorithm.
It tries its best to respect the print_width, but will sometimes overflow.
So this is working as expected.

Thank you for the very thorough report though and sorry for the delay in answering.

**Comment by awalterschulze** [comment]
Good idea, how about https://github.com/WhatsApp/erlfmt/pull/303

**Comment by eproxus** [comment]
@awalterschulze Great, thanks! 🙇
