### ISSUE TITLE
Failure to format rebar3 substituted vars in sys_config_src

### ISSUE THREAD

**Issue by stratacast** [WhatsApp/erlfmt#347]
Example piece of sys_config_src:

``` erlang
[
  {kernel,
   [{logger_level, ${LOGLEVEL}},
    {logger,
     [{handler, my_std_h, logger_std_h,
       #{ config => #{ file => "/home/${USER}/log/erlang.log",
                       max_no_bytes => 4096000,
                       max_no_files => 5},
          formatter => {logger_formatter, #{template => [time," [",level,"]: ",msg,"\n"], single_line => false}}}}]}]}

].
```

Should format to:

``` erlang
[
    {kernel, [
        {logger_level, ${LOGLEVEL}},
        {logger, [
            {handler, my_std_h, logger_std_h, #{
                config => #{
                    file => "/home/${USER}/log/erlang.log",
                    max_no_bytes => 4096000,
                    max_no_files => 5
                },
                formatter =>
                    {logger_formatter, #{
                        template => [time, " [", level, "]: ", msg, "\n"], single_line => false
                    }}
            }}
        ]}
    ]}
].
```

But instead I get this error: `config/sys.config.src:1:1: syntax error before: '['`

The culprit is at `{logger_level, ${LOGLEVEL}},`. This templated var is not enclosed in quotation marks, because the value is an atom. If I wrap `${LOGLEVEL}` in quotation marks, the formatting works. There appears to be an issue in erlfmt formatting templated atom values.

**Comment by stratacast** [comment]
That works! Thank you for pointing out the single quotes.

**Comment by chsukivra** [comment]
Any similar trick to quote expansion of values that are numeric?

I can only think of making my app able to accept an integer OR string, and in the later case do list_to_integer on that value in my code.
