### ISSUE TITLE
unicode "张三" in erlang source file will be replaced to "\x{5F20}\x{4E09}"

### ISSUE THREAD

**Issue by yushli** [WhatsApp/erlfmt#349]
The following unicode "张三" in erlang source file will be replaced to "\x{5F20}\x{4E09}". Is there a config to control this? Thanks for the reply.

**Comment by michalmuskala** [comment]
I can't reproduce this behaviour. Is the original file in UTF8 encoding?

When running locally I get the expected result:
```
$ echo 'foo() -> "张三".' | erlfmt -
foo() -> "张三".
```

**Comment by yushli** [comment]
I tried and looks like it is not erlfmt's issue. I am using JsPrettier with erlfmt to support Erlang source code formatting. It seems to be some issue with the communication between them. Thanks for looking into this and provide the quick response.
