### ISSUE TITLE
OPT 27's `-moduledoc """` makes `erlfmt` fail

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [WhatsApp/erlfmt#355]
Failure is something like `_build/default/plugins/erlfmt/src/erlfmt_parse.yrl:98:71: Warning: expression updates a literal`

I'm guessing you're aware of the issue, by now, but this can serve as a way to follow-up on when a fix is coming. 👍 

Thanks.

**Comment by michalmuskala** [comment]
Yes, we need to properly support all the OTP 27 new syntax - triple quotes, the `-doc` attributes and string sigils.

**Comment by rlipscombe** [comment]
This also seems to be the cause of crashes in the erlang-ls extension in VS Code when browsing the OTP 27 source code.
