### ISSUE TITLE
Allow reading from stdin

### ISSUE THREAD

**Issue by ehamberg** [WhatsApp/erlfmt#46]
It would be great if erlfmt supported reading from `stdin` (e.g. when passed `--stdin`) so that it can be used by editor plugins such as https://github.com/lassik/emacs-format-all-the-code that pass a buffer's content to the formatter instead of operating on a file on disk.

**Comment by awalterschulze** [comment]
This is a great idea :) We will look into adding it.

**Comment by awalterschulze** [comment]
This feature is being added in https://github.com/WhatsApp/erlfmt/pull/50

Thanks again for the great idea :)

**Comment by ehamberg** [comment]
Thank you so much! Works great!

In case any doom emacs users stumble over this issue: You can now use erlfmt to format erlang buffers by adding the following to `config.el`:

```elisp
(set-formatter! 'erlfmt  "erlfmt -" :modes '(erlang-mode))
```

**Comment by awalterschulze** [comment]
Happy to hear it works so well :)

Maybe we should make even easier to spot this tip.
https://github.com/WhatsApp/erlfmt/pull/55

**Comment by Benjamin-Philip** [comment]
> Thank you so much! Works great!
> 
> In case any doom emacs users stumble over this issue: You can now use erlfmt to format erlang buffers by adding the following to `config.el`:
> 
> ```emacs-lisp
> (set-formatter! 'erlfmt  "erlfmt -" :modes '(erlang-mode))
> ```

This does not seem to work with rebar3:

```emacs-lisp
 (set-formatter! 'erlfmt  "rebar3 fmt -" :modes '(erlang-mode))
```

Could you update your comment to what you use now, incase there has been some change to `set-formatter!`?

**Comment by ehamberg** [comment]
> Could you update your comment to what you use now, incase there has been some change to `set-formatter!`?

I still use the same config. However, I don't use `erlfmt` through `rebar3`, I call it directly. Not sure if `rebar3 fmt` supports reading from `stdin`.

**Comment by michalmuskala** [comment]
Even if reading from stdin with rebar3 worked fine, I think outputting to stdout might actually not - rebar3 output is quite verbose and sometimes quite random if things go to stdout or stderr. With standalone escript we can control it all, but running as a rebar3 plugin this is more complicated.
