### ISSUE TITLE
Preserve empty lines in export lists

### ISSUE THREAD

**Issue by awalterschulze** [WhatsApp/erlfmt#72]
```erlang
-export([
  % comment
  a/2,

  % another group
  b/1
]).
```

**Comment by michalmuskala** [comment]
I wonder if we should expand that to all collections preserving empty lines between elements

**Comment by awalterschulze** [comment]
That sounds very interesting.  Is there maybe an example where we think this would be useful?

**Comment by michalmuskala** [comment]
In the same case as for exports - grouping in a long list, for example. See how it's used in Elixir that has this behaviour in the formatter https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/code/formatter.ex#L54-L137

**Comment by awalterschulze** [comment]
I am trying to find examples or counter examples of this in erlang code, but somehow I am failing to find long lists, that aren't export statements.  I feel like I need a code analysis tool.

**Comment by awalterschulze** [comment]
But I can't really see the downside here either.
