### ISSUE TITLE
Don't preserve operator newline with a next break fits expression

### ISSUE THREAD

**Issue by michalmuskala** [WhatsApp/erlfmt#92]
For example, today we keep the following code as-is
```erlang
Foo = 
    [
        1,
        2
    ].
```
But we also keep the following as-is since lists are "next break fits":
```erlang
Foo = [
    1,
    2
].
```

We should consider if we shouldn't always hard-format to the second form. This is what the elixir formatter does.

**Comment by awalterschulze** [comment]
Yes I like the second form, but is it consistent for other containers and just remind me when is the first form preferred.

**Comment by michalmuskala** [comment]
We would do this change consistently for other formatters.

Preserving newlines was introduced in https://github.com/WhatsApp/erlfmt/commit/28a9d5eb29827d8d11de27fff569f0d7e8ebd2ae. The motivating example there was
```erlang
Foo andalso
    Bar andalso
    Baz
```

`=` was "trapped" there by accident
