### ISSUE TITLE
Comments: Rethink formatting of function with spec and comment

### ISSUE THREAD

**Issue by awalterschulze** [WhatsApp/erlfmt#94]
Given the following input

```erlang
-spec get_service_name(client:api()) -> atom().
get_service_name(_API) -> name. % sync with name.app.src
```

It is formatted too

```erlang
-spec get_service_name(client:api()) -> atom().
% sync with name.app.src
get_service_name(_API) -> name.
```

Better options are:

1. 
```erlang
-spec get_service_name(client:api()) -> atom().
get_service_name(_API) -> name. % sync with name.app.src
```
2. 
```erlang
-spec get_service_name(client:api()) -> atom().
get_service_name(_API) ->
  % sync with name.app.src
  name.
```
3.
```erlang
% sync with name.app.src
-spec get_service_name(client:api()) -> atom().
get_service_name(_API) -> name.
```

Where number 1 has gotten a vote and number 3 has gotten at least one vote and one settle.

**Comment by michalmuskala** [comment]
The main complexity in this seems to be - what to do in cases where the comment is in the middle in the first place, e.g.

```erlang
-spec get_service_name(client:api()) -> atom().
% sync with name.app.src
get_service_name(_API) -> name.
```

and also what to do in case of multiple clauses
```erlang
-spec get_service_name(client:api()) -> atom().
get_service_name(#{override: Name}) -> Name; % override
get_service_name(_) -> name. % sync with name.app.src

```

**Comment by ruippeixotog** [comment]
The second case as an interesting one! It seems like a good argument to choose option 2 as a more general approach (since comments may be related to specific clauses).

**Comment by TheGeorge** [comment]
I think comment placement should not be changed significantly by the formatter. The coder usually has something in mind placing them. I think it's wrong moving them to other places.

I think 1. is the only right option.

**Comment by awalterschulze** [comment]
We have had another report about comments with spec
"""
I usually write `%% @private` between a function's `-spec(_).` and its declaration, like so:

```erlang
-spec add(A :: integer(), B :: integer()) -> integer().
%% @private
add(A, B) ->
```

`erlfmt` prefers it like
```erlang
-spec add(A :: integer(), B :: integer()) -> integer().
    %% @private
add(A, B) ->
```
"""

**Comment by michalmuskala** [comment]
This last case looks like a bug to me. I don't think we should be doing anything like this.

**Comment by awalterschulze** [comment]
I agree :)

**Comment by awalterschulze** [comment]
I have retested with master version of erlfmt and the bug does not occur any more.

**Comment by awalterschulze** [comment]
After doing more analyses on comments, we have decided that adding support for trailing comments is a good idea https://github.com/WhatsApp/erlfmt/issues/219

Doing it will require a lot of work, so no promises on when this will be delivered, but I believe we can consider this issue a duplicate, because if we support trailing comments, then this wouldn't have been an issue.

I hope that makes sense.
